## EDA = Exploratory Data Analysis

In [1]:
import pandas as pd
import numpy as np
import os
import warnings; warnings.filterwarnings("ignore")
import matplotlib.pyplot as plt
import seaborn as sns
import plotly as px

In [9]:
os.listdir('../data/raw/')

['12_apple_global_sales_dataset.csv']

In [10]:
df = pd.read_csv('../data/raw/12_apple_global_sales_dataset.csv')

In [12]:
df.sample(2)

,sale_id,sale_date,year,quarter,month,country,region,city,product_name,category,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
9549,APPL-00009550,2024-09-02,2024,Q3,September,Sweden,Europe,Örebro,iPhone 13 Pro Max,iPhone,...,SEK,10.55,23642.97,Apple Store,Cash,Education,18–24,iOS 17,5.0,Returned
3097,APPL-00003098,2022-12-12,2022,Q4,December,Finland,Europe,Oulu,AirPods Pro (2nd Gen),AirPods,...,EUR,0.92,191.31,Apple Store,Apple Pay,Business,55+,NaN,NaN,Kept

In [13]:
df.drop('sale_id', axis= 1 , inplace=True)

In [15]:
df.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
8974,2024-11-17,2024,Q4,November,South Korea,Asia,Incheon,AirPods Pro (2nd Gen),AirPods,NaN,...,KRW,1328.0,309716.16,Corporate / B2B,Gift Card,Individual,18–24,NaN,4.1,Kept

In [16]:
df.isna().sum()

sale_date                    0
year                         0
quarter                      0
month                        0
country                      0
region                       0
city                         0
product_name                 0
category                     0
storage                   4804
color                        0
unit_price_usd               0
discount_pct                 0
units_sold                   0
discounted_price_usd         0
revenue_usd                  0
currency                     0
fx_rate_to_usd               0
revenue_local_currency       0
sales_channel                0
payment_method               0
customer_segment             0
customer_age_group           0
previous_device_os        8056
customer_rating           3360
return_status                0
dtype: int64

# Storage

In [35]:
df["storage"].value_counts()

storage
64 GB         944
256 GB        941
512 GB        924
128 GB        903
1 TB          889
1 TB SSD      473
2 TB SSD      472
512 GB SSD    471
256 GB SSD    457
2 TB          222
Name: count, dtype: int64

In [18]:
df["storage"].unique()

<ArrowStringArray>
[         nan,   '1 TB SSD',      '64 GB',     '128 GB',     '256 GB',
       '1 TB',   '2 TB SSD',     '512 GB', '512 GB SSD',       '2 TB',
 '256 GB SSD']
Length: 11, dtype: str

In [25]:
df[ df["storage"].isna()].sample(5)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
8487,2023-12-12,2023,Q4,December,Singapore,Asia,Singapore,Apple Watch Ultra 2,Apple Watch,NaN,...,SGD,1.34,2952.69,Apple Store,Credit Card,Government,35–44,NaN,4.1,Kept
8391,2022-07-08,2022,Q3,July,Singapore,Asia,Singapore,Apple Watch Series 9,Apple Watch,NaN,...,SGD,1.34,1043.57,Authorized Reseller,Debit Card,Government,55+,NaN,5.0,Kept
8593,2024-02-09,2024,Q1,February,South Africa,Africa,Bloemfontein,Magic Mouse,Accessories,NaN,...,ZAR,18.90,4311.47,Online (Apple.com),EMI / Installment,Individual,55+,NaN,4.2,Kept
4350,2023-09-29,2023,Q3,September,Indonesia,Asia,Surabaya,AirPods Pro (2nd Gen),AirPods,NaN,...,IDR,15700.00,3532971.00,Corporate / B2B,Net Banking,Government,45–54,NaN,3.3,Kept
3253,2024-01-19,2024,Q1,January,France,Europe,Lille,Magic Trackpad,Accessories,NaN,...,EUR,0.92,99.30,Corporate / B2B,Gift Card,Business,18–24,NaN,5.0,Kept

# previous_device_os

In [26]:
df["previous_device_os"].unique()

<ArrowStringArray>
[nan, 'iOS 16', 'New User', 'Other', 'iOS 15', 'Android', 'iOS 17']
Length: 7, dtype: str

In [33]:
df["previous_device_os"].value_counts()

previous_device_os
Android     595
iOS 16      587
Other       581
New User    571
iOS 15      556
iOS 17      554
Name: count, dtype: int64

In [29]:
df[ df["previous_device_os"].isna()].sample(10)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
3932,2024-02-16,2024,Q1,February,Hong Kong,Asia,Yuen Long,Apple Watch SE (2nd Gen),Apple Watch,NaN,...,HKD,7.82,5404.25,Online (Apple.com),Apple Pay,Education,35–44,NaN,NaN,Kept
8046,2024-07-20,2024,Q3,July,Russia,Europe/Asia,Samara,Apple Pencil (2nd Gen),Accessories,NaN,...,RUB,91.50,22269.27,Authorized Reseller,Apple Pay,Education,55+,NaN,NaN,Kept
880,2023-02-21,2023,Q1,February,Bangladesh,Asia,Mymensingh,iPad Pro 11-inch (M2),iPad,512 GB,...,BDT,110.00,338065.20,Carrier Store,Net Banking,Government,55+,NaN,3.0,Kept
4106,2022-10-29,2022,Q4,October,India,Asia,Rajkot,Apple Pencil (2nd Gen),Accessories,NaN,...,INR,83.50,11366.02,Corporate / B2B,Net Banking,Business,45–54,NaN,3.9,Kept
11213,2022-12-20,2022,Q4,December,United States,North America,Philadelphia,MacBook Air 13-inch (M2),Mac,1 TB SSD,...,USD,1.00,2135.64,Carrier Store,Credit Card,Business,18–24,NaN,4.1,Kept
6035,2023-05-10,2023,Q2,May,Netherlands,Europe,Groningen,Mac mini (M2),Mac,2 TB SSD,...,EUR,0.92,495.92,Third-Party Retailer,Net Banking,Government,18–24,NaN,3.9,Kept
4285,2022-09-23,2022,Q3,September,Indonesia,Asia,Palembang,Apple Watch SE (2nd Gen),Apple Watch,NaN,...,IDR,15700.00,6789622.00,Online (Apple.com),Net Banking,Individual,25–34,NaN,4.0,Kept
5185,2022-04-04,2022,Q2,April,Kenya,Africa,Kisumu,Magic Keyboard,Accessories,NaN,...,KES,129.00,12487.20,Third-Party Retailer,Net Banking,Individual,18–24,NaN,3.9,Returned
4864,2023-02-27,2023,Q1,February,Italy,Europe,Verona,AirPods (2nd Gen),AirPods,NaN,...,EUR,0.92,323.25,Authorized Reseller,EMI / Installment,Business,45–54,NaN,4.6,Returned
7821,2022-05-03,2022,Q2,May,Portugal,Europe,Porto,iPad Mini (6th Gen),iPad,128 GB,...,EUR,0.92,483.92,Online (Apple.com),Cash,Business,25–34,NaN,NaN,Kept