## EDA = Exploratory Data Analysis

In [1]:
import pandas as pd
import numpy as np
import os
import warnings; warnings.filterwarnings("ignore")
import matplotlib.pyplot as plt
import seaborn as sns
import plotly as px
# pip install streamlit-option-menu
# from streamlit_option_menu import option_menu

In [2]:
os.listdir('../data/raw/')

['12_apple_global_sales_dataset.csv']

In [3]:
df = pd.read_csv('../data/raw/12_apple_global_sales_dataset.csv')

In [4]:
df.shape

(11500, 27)

In [5]:
df.sample(2)

,sale_id,sale_date,year,quarter,month,country,region,city,product_name,category,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
4025,APPL-00004026,2023-02-21,2023,Q1,February,India,Asia,Kanpur,iPhone 13 Mini,iPhone,...,INR,83.5,53880.88,Apple Store,Net Banking,Government,35–44,Android,3.5,Kept
4192,APPL-00004193,2023-09-19,2023,Q3,September,Indonesia,Asia,Bekasi,iPhone 13,iPhone,...,IDR,15700.0,10692485.00,Carrier Store,Gift Card,Individual,18–24,iOS 16,3.6,Kept

In [6]:
df.drop('sale_id', axis= 1 , inplace=True)

In [7]:
df.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
451,2022-10-21,2022,Q4,October,Australia,Oceania,Newcastle,Apple TV 4K (3rd Gen),Accessories,NaN,...,AUD,1.53,336.57,Corporate / B2B,Gift Card,Education,55+,NaN,3.6,Kept

In [8]:
df.isna().sum()

sale_date                    0
year                         0
quarter                      0
month                        0
country                      0
region                       0
city                         0
product_name                 0
category                     0
storage                   4804
color                        0
unit_price_usd               0
discount_pct                 0
units_sold                   0
discounted_price_usd         0
revenue_usd                  0
currency                     0
fx_rate_to_usd               0
revenue_local_currency       0
sales_channel                0
payment_method               0
customer_segment             0
customer_age_group           0
previous_device_os        8056
customer_rating           3360
return_status                0
dtype: int64

# Storage

In [9]:
df["storage"].value_counts()

storage
64 GB         944
256 GB        941
512 GB        924
128 GB        903
1 TB          889
1 TB SSD      473
2 TB SSD      472
512 GB SSD    471
256 GB SSD    457
2 TB          222
Name: count, dtype: int64

In [10]:
df["storage"].unique()

array([nan, '1 TB SSD', '64 GB', '128 GB', '256 GB', '1 TB', '2 TB SSD',
       '512 GB', '512 GB SSD', '2 TB', '256 GB SSD'], dtype=object)

In [11]:
df["storage"].isna().sum()

np.int64(4804)

# previous_device_os

In [12]:
df["previous_device_os"].unique()

array([nan, 'iOS 16', 'New User', 'Other', 'iOS 15', 'Android', 'iOS 17'],
      dtype=object)

In [13]:
df["previous_device_os"].value_counts()

previous_device_os
Android     595
iOS 16      587
Other       581
New User    571
iOS 15      556
iOS 17      554
Name: count, dtype: int64

In [14]:
df[ df["previous_device_os"].isna()].sample(10)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
7393,2022-02-14,2022,Q1,February,Poland,Europe,Gdansk,iPad Pro 11-inch (M2),iPad,128 GB,...,PLN,3.97,2625.20,Corporate / B2B,EMI / Installment,Individual,25–34,NaN,3.5,Kept
1946,2024-06-18,2024,Q2,June,Chile,South America,Valparaíso,USB-C Woven Charge Cable,Accessories,NaN,...,CLP,960.00,56736.00,Third-Party Retailer,Cash,Business,55+,NaN,NaN,Kept
10580,2024-04-08,2024,Q2,April,UAE,Middle East,Abu Dhabi,Mac mini (M2),Mac,512 GB SSD,...,AED,3.67,2305.09,Third-Party Retailer,EMI / Installment,Government,18–24,NaN,4.9,Kept
6613,2023-10-29,2023,Q4,October,Nigeria,Africa,Maiduguri,MacBook Pro 16-inch (M3 Pro),Mac,2 TB SSD,...,NGN,1550.00,3605393.00,Corporate / B2B,Credit Card,Education,45–54,NaN,4.5,Kept
8091,2024-03-24,2024,Q1,March,Russia,Europe/Asia,Yekaterinburg,MacBook Air 13-inch (M2),Mac,256 GB SSD,...,RUB,91.50,189882.63,Carrier Store,Cash,Government,35–44,NaN,4.4,Kept
7959,2024-02-03,2024,Q1,February,Russia,Europe/Asia,Novosibirsk,Apple TV 4K (3rd Gen),Accessories,NaN,...,RUB,91.50,47265.24,Carrier Store,Debit Card,Education,55+,NaN,4.3,Kept
3559,2023-01-14,2023,Q1,January,Germany,Europe,Frankfurt,iPad Air (M1),iPad,512 GB,...,EUR,0.92,571.37,Third-Party Retailer,Net Banking,Education,25–34,NaN,3.7,Kept
5977,2024-10-01,2024,Q4,October,Netherlands,Europe,Amsterdam,Apple Pencil (2nd Gen),Accessories,NaN,...,EUR,0.92,252.21,Authorized Reseller,Credit Card,Individual,45–54,NaN,NaN,Returned
10603,2022-11-14,2022,Q4,November,UAE,Middle East,Ajman,iPad Air (M1),iPad,512 GB,...,AED,3.67,4410.31,Third-Party Retailer,Credit Card,Government,25–34,NaN,4.1,Kept
445,2022-01-16,2022,Q1,January,Australia,Oceania,Newcastle,iMac 24-inch (M3),Mac,2 TB SSD,...,AUD,1.53,1601.77,Online (Apple.com),Net Banking,Individual,35–44,NaN,5.0,Kept

# customer_rating

In [15]:
df["customer_rating"].value_counts()

customer_rating
4.0    434
4.4    433
4.6    433
3.7    432
3.2    428
4.2    426
3.4    422
4.8    414
4.3    413
3.5    407
4.1    405
3.9    399
3.6    399
3.3    398
4.7    394
4.9    393
3.8    376
3.1    373
4.5    366
3.0    198
5.0    197
Name: count, dtype: int64

In [16]:
df ["customer_rating"].isna().sum()

np.int64(3360)

In [17]:
df[ df ["customer_rating"].isna()].sample(10)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
5276,2022-02-25,2022,Q1,February,Kenya,Africa,Mombasa,iPhone 14 Pro,iPhone,1 TB,...,KES,129.00,106632.69,Corporate / B2B,Gift Card,Individual,45–54,Other,NaN,Kept
8807,2022-05-17,2022,Q2,May,South Korea,Asia,Busan,iPhone 14 Plus,iPhone,512 GB,...,KRW,1328.00,1134178.40,Carrier Store,Gift Card,Government,55+,Android,NaN,Kept
9680,2023-08-06,2023,Q3,August,Switzerland,Europe,Lucerne,Apple Watch Ultra 2,Apple Watch,NaN,...,CHF,0.88,631.30,Corporate / B2B,Credit Card,Government,25–34,NaN,NaN,Kept
9169,2024-12-28,2024,Q4,December,Spain,Europe,Madrid,Apple Watch Ultra 2,Apple Watch,NaN,...,EUR,0.92,659.14,Apple Store,Debit Card,Government,18–24,NaN,NaN,Exchanged
7866,2022-08-17,2022,Q3,August,Russia,Europe/Asia,Chelyabinsk,AirPods Max,AirPods,NaN,...,RUB,91.50,44276.85,Online (Apple.com),Net Banking,Business,35–44,NaN,NaN,Kept
2863,2023-05-15,2023,Q2,May,Egypt,Africa,Shubra El Kheima,Mac Pro (M2 Ultra),Mac,512 GB SSD,...,EGP,30.90,179402.62,Third-Party Retailer,EMI / Installment,Government,35–44,NaN,NaN,Kept
8563,2024-10-29,2024,Q4,October,Singapore,Asia,Singapore,iPhone 14 Pro,iPhone,128 GB,...,SGD,1.34,2348.11,Online (Apple.com),Net Banking,Business,18–24,iOS 15,NaN,Kept
146,2023-11-09,2023,Q4,November,Argentina,South America,Mendoza,MacBook Pro 16-inch (M3 Pro),Mac,1 TB SSD,...,ARS,907.00,7106979.90,Apple Store,Debit Card,Business,55+,NaN,NaN,Kept
5150,2022-01-04,2022,Q1,January,Kenya,Africa,Eldoret,MacBook Air 15-inch (M2),Mac,2 TB SSD,...,KES,129.00,170812.77,Corporate / B2B,Gift Card,Government,55+,NaN,NaN,Kept
11223,2024-10-29,2024,Q4,October,United States,North America,Philadelphia,Magic Trackpad,Accessories,NaN,...,USD,1.00,122.00,Authorized Reseller,Net Banking,Government,45–54,NaN,NaN,Kept

# Duplicated

In [18]:
df.duplicated().sum()

np.int64(0)

In [19]:
df.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
4014,2022-12-30,2022,Q4,December,India,Asia,Jaipur,iPhone SE (3rd Gen),iPhone,1 TB,...,INR,83.5,33197.93,Carrier Store,Apple Pay,Government,18–24,iOS 17,NaN,Kept

In [20]:
df["sale_date"].unique()

array(['2022-01-03', '2022-01-04', '2022-05-18', ..., '2024-04-06',
       '2024-03-13', '2024-08-12'], shape=(1096,), dtype=object)

In [21]:
df.columns

Index(['sale_date', 'year', 'quarter', 'month', 'country', 'region', 'city',
       'product_name', 'category', 'storage', 'color', 'unit_price_usd',
       'discount_pct', 'units_sold', 'discounted_price_usd', 'revenue_usd',
       'currency', 'fx_rate_to_usd', 'revenue_local_currency', 'sales_channel',
       'payment_method', 'customer_segment', 'customer_age_group',
       'previous_device_os', 'customer_rating', 'return_status'],
      dtype='object')

# Year 2022
- Q1
- Q2
- Q3
- Q4

# Start Here

In [22]:
All_Sales_price = round(df["unit_price_usd"].sum())
All_orders = df.shape[0]

All_Sales_price, All_orders

(9290289, 11500)

In [23]:
year2022 = df [df['year'] == 2022]

year2022

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
0,2022-01-03,2022,Q1,January,Argentina,South America,Buenos Aires,AirPods (3rd Gen),AirPods,NaN,...,ARS,907.0,1.343448e+05,Third-Party Retailer,Cash,Government,45–54,NaN,4.1,Kept
1,2022-01-04,2022,Q1,January,Argentina,South America,Buenos Aires,USB-C Woven Charge Cable,Accessories,NaN,...,ARS,907.0,1.155971e+05,Authorized Reseller,Debit Card,Business,45–54,NaN,4.8,Kept
2,2022-05-18,2022,Q2,May,Argentina,South America,Buenos Aires,Apple Watch Series 8,Apple Watch,NaN,...,ARS,907.0,1.066342e+06,Corporate / B2B,Credit Card,Individual,18–24,NaN,4.3,Kept
3,2022-05-23,2022,Q2,May,Argentina,South America,Buenos Aires,MacBook Pro 14-inch (M3),Mac,1 TB SSD,...,ARS,907.0,3.506045e+06,Carrier Store,Credit Card,Education,45–54,NaN,NaN,Kept
4,2022-07-13,2022,Q3,July,Argentina,South America,Buenos Aires,Apple Watch Ultra 2,Apple Watch,NaN,...,ARS,907.0,1.952780e+06,Apple Store,Net Banking,Education,18–24,NaN,NaN,Kept
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11476,2022-06-02,2022,Q2,June,Vietnam,Asia,Nha Trang,Mac mini (M2),Mac,512 GB SSD,...,VND,24500.0,1.373274e+07,Carrier Store,Gift Card,Business,45–54,NaN,3.1,Exchanged
11477,2022-07-01,2022,Q3,July,Vietnam,Asia,Nha Trang,iPhone 14 Pro,iPhone,512 GB,...,VND,24500.0,1.842620e+07,Corporate / B2B,EMI / Installment,Government,18–24,New User,NaN,Exchanged
11478,2022-07-09,2022,Q3,July,Vietnam,Asia,Nha Trang,Mac Pro (M2 Ultra),Mac,512 GB SSD,...,VND,24500.0,1.700905e+08,Authorized Reseller,Gift Card,Education,25–34,NaN,4.8,Kept
11479,2022-07-15,2022,Q3,July,Vietnam,Asia,Nha Trang,iPad Air (M1),iPad,256 GB,...,VND,24500.0,1.369354e+07,Online (Apple.com),Debit Card,Education,25–34,NaN,3.1,Kept
11480,2022-07-31,2022,Q3,July,Vietnam,Asia,Nha Trang,iPhone SE (3rd Gen),iPhone,128 GB,...,VND,24500.0,9.481255e+06,Authorized Reseller,Credit Card,Education,45–54,Other,NaN,Kept

# 2022 Sum + sum price

In [24]:
year2022_sum = len (year2022)
year2022_sum_price = round(year2022["unit_price_usd"].sum())

year2022_sum, year2022_sum_price

(3898, 3042749)

# 2022 | Q1

In [25]:
Q1_y_2022 = year2022[year2022['quarter'] == 'Q1']

Q1_y_2022.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
6050,2022-03-02,2022,Q1,March,Netherlands,Europe,Nijmegen,USB-C Woven Charge Cable,Accessories,NaN,...,EUR,0.92,48.15,Apple Store,Credit Card,Government,45–54,NaN,NaN,Kept

In [26]:
Q1_y_2022_sum = len (Q1_y_2022)
Q1_y_2022_sum_price = round( Q1_y_2022["unit_price_usd"].sum())

Q1_y_2022_sum, Q1_y_2022_sum_price

(970, 774161)

# 2022 | Q2

In [27]:
Q2_y_2022 = year2022[year2022['quarter'] == 'Q2']

Q2_y_2022.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
7110,2022-06-18,2022,Q2,June,Philippines,Asia,Antipolo,iPhone 13 Pro,iPhone,128 GB,...,PHP,56.5,45267.8,Apple Store,Net Banking,Business,45–54,iOS 16,4.1,Kept

In [28]:
Q2_y_2022_sum = len (Q2_y_2022)
Q2_y_2022_sum_price = round(Q2_y_2022["unit_price_usd"].sum())

Q2_y_2022_sum, Q2_y_2022_sum_price

(946, 729307)

# 2022 | Q3

In [29]:
Q3_y_2022 = year2022[year2022['quarter'] == 'Q3']

Q3_y_2022.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
9244,2022-08-01,2022,Q3,August,Spain,Europe,Valladolid,AirPods Max,AirPods,NaN,...,EUR,0.92,1199.25,Authorized Reseller,Debit Card,Individual,35–44,NaN,NaN,Kept

In [30]:
Q3_y_2022_sum = len (Q3_y_2022)
Q3_y_2022_sum_price = round(Q3_y_2022["unit_price_usd"].sum())

Q3_y_2022_sum, Q3_y_2022_sum_price

(978, 782178)

# 2022 | Q4

In [31]:
Q4_y_2022 = year2022[year2022['quarter'] == 'Q4']

Q4_y_2022.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
1452,2022-10-10,2022,Q4,October,Canada,North America,Calgary,iPhone SE (3rd Gen),iPhone,256 GB,...,CAD,1.36,525.04,Online (Apple.com),EMI / Installment,Business,18–24,iOS 15,NaN,Kept

In [32]:
Q4_y_2022_sum = len (Q4_y_2022)
Q4_y_2022_sum_price = round(Q4_y_2022["unit_price_usd"].sum())

Q4_y_2022_sum, Q4_y_2022_sum_price

(1004, 757103)

# Year 2023

In [33]:
year2023 = df [df['year'] == 2023]

year2023.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
10756,2023-05-29,2023,Q2,May,UAE,Middle East,Sharjah,Magic Mouse,Accessories,NaN,...,AED,3.67,558.28,Corporate / B2B,Debit Card,Government,45–54,NaN,4.2,Kept

# 2023 sum + sum Price

In [34]:
year2023_sum = len (year2023)
year2023_sum_price = round(year2023["unit_price_usd"].sum(),  )

year2023_sum, year2023_sum_price

(3735, 3043959)

# 2023 | Q1

In [35]:
Q1_y_2023 = year2023[year2023["quarter"] == 'Q1']

Q1_y_2023.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
106,2023-02-27,2023,Q1,February,Argentina,South America,Mar del Plata,Mac Pro (M2 Ultra),Mac,512 GB SSD,...,ARS,907.0,18262290.81,Online (Apple.com),Gift Card,Individual,35–44,NaN,3.4,Kept

In [36]:
Q1_y_2023_sum = len (Q1_y_2023)
Q1_y_2023_sum_price = round(Q1_y_2023["unit_price_usd"].sum())

Q1_y_2023_sum, Q1_y_2023_sum_price

(945, 801912)

# 2023 | Q2

In [37]:
Q2_y_2023 = year2023[year2023["quarter"] == 'Q2']

Q2_y_2023.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
9342,2023-06-04,2023,Q2,June,Sweden,Europe,Helsingborg,Apple Watch SE (2nd Gen),Apple Watch,NaN,...,SEK,10.55,2711.98,Carrier Store,Cash,Business,35–44,NaN,NaN,Kept

In [38]:
Q2_y_2023_sum = len (Q2_y_2023)
Q2_y_2023_sum_price = round(Q2_y_2023["unit_price_usd"].sum())

Q2_y_2023_sum, Q2_y_2023_sum_price

(934, 757829)

#  2023 | Q3

In [39]:
Q3_y_2023 = year2023[year2023["quarter"] == 'Q3']

Q3_y_2023.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
6731,2023-09-15,2023,Q3,September,Norway,Europe,Kristiansand,iPad Pro 11-inch (M2),iPad,256 GB,...,NOK,10.65,27092.32,Carrier Store,Cash,Government,35–44,NaN,4.7,Kept

In [40]:
Q3_y_2023_sum = len (Q3_y_2023)
Q3_y_2023_sum_price = round(Q3_y_2023["unit_price_usd"].sum())

Q3_y_2023_sum, Q3_y_2023_sum_price

(920, 730480)

# 2023 | Q4

In [41]:
Q4_y_2023 = year2023[year2023["quarter"] == 'Q4']

Q4_y_2023.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
565,2023-10-25,2023,Q4,October,Austria,Europe,Graz,iPhone 13,iPhone,128 GB,...,EUR,0.92,615.34,Authorized Reseller,EMI / Installment,Government,35–44,Android,4.8,Kept

In [42]:
Q4_y_2023_sum = len (Q4_y_2023)
Q4_y_2023_sum_price = round( Q4_y_2023["unit_price_usd"].sum())

Q4_y_2023_sum, Q4_y_2023_sum_price

(936, 753738)

# Year 2024

In [43]:
year2024 = df [df['year'] == 2024]

year2024.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
10220,2024-01-02,2024,Q1,January,Thailand,Asia,Nonthaburi,Apple Watch Series 8,Apple Watch,NaN,...,THB,35.2,10262.91,Authorized Reseller,Net Banking,Government,25–34,NaN,4.8,Kept

In [44]:
year2024_sum = len (year2024)
year2024_sum_price = round(year2024["unit_price_usd"].sum())

year2024_sum, year2024_sum_price

(3867, 3203581)

# 2024 | Q1

In [45]:
Q1_y_2024 = year2024[ year2024["quarter"] == 'Q1']

Q1_y_2024.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
1428,2024-01-28,2024,Q1,January,Brazil,South America,São Luís,MacBook Air 13-inch (M2),Mac,2 TB SSD,...,BRL,4.97,10170.51,Apple Store,Gift Card,Business,35–44,NaN,NaN,Kept

In [46]:
Q1_y_2024_sum = len (Q1_y_2024)
Q1_y_2024_sum_price = round(Q1_y_2024["unit_price_usd"].sum())

Q1_y_2024_sum, Q1_y_2024_sum_price

(979, 795100)

# 2024 | Q2

In [47]:
Q2_y_2024 = year2024[ year2024["quarter"] == 'Q2']

Q2_y_2024.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
9423,2024-04-02,2024,Q2,April,Sweden,Europe,Malmö,iPhone 15,iPhone,128 GB,...,SEK,10.55,8254.95,Carrier Store,Cash,Business,45–54,New User,4.4,Kept

In [48]:
Q2_y_2024_sum = len (Q2_y_2024)
Q2_y_2024_sum_price = round(Q2_y_2024["unit_price_usd"].sum())

Q2_y_2024_sum, Q2_y_2024_sum_price

(940, 744294)

# 2024 | Q3

In [49]:
Q3_y_2024 = year2024[ year2024["quarter"] == 'Q3']

Q3_y_2024.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
5752,2024-07-16,2024,Q3,July,Mexico,North America,Mexico City,Magic Mouse,Accessories,NaN,...,MXN,17.15,3914.83,Apple Store,EMI / Installment,Government,35–44,NaN,4.7,Kept

In [50]:
Q3_y_2024_sum = len (Q3_y_2024)
Q3_y_2024_sum_price = round(Q3_y_2024["unit_price_usd"].sum())

Q3_y_2024_sum, Q3_y_2024_sum_price

(966, 793215)

# 2024 | Q4

In [51]:
Q4_y_2024 = year2024[ year2024["quarter"] == 'Q4']

Q4_y_2024.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
2383,2024-10-20,2024,Q4,October,Colombia,South America,Medellín,iPhone 13 Mini,iPhone,512 GB,...,COP,3960.0,2149369.2,Apple Store,Debit Card,Business,18–24,iOS 15,4.8,Kept

In [52]:
Q4_y_2024_sum = len (Q4_y_2024)
Q4_y_2024_sum_price = round(Q4_y_2024["unit_price_usd"].sum())

Q4_y_2024_sum, Q4_y_2024_sum_price

(982, 870971)

# Unit price usd

In [53]:
All_unit_price = round(df["unit_price_usd"].sum())

All_unit_price

9290289

# min Pirce, mean Price, max Price

In [54]:
All_min_price = round(df["unit_price_usd"].min())
All_mean_price = round(df["unit_price_usd"].mean())
All_max_price = round(df["unit_price_usd"].max())

All_min_price,All_mean_price, All_max_price

(27, 808, 7551)

In [55]:
# Controll:
year2022_sum_price + year2023_sum_price + year2024_sum_price

9290289

# Region

In [56]:
df.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
6278,2022-04-30,2022,Q2,April,New Zealand,Oceania,Hamilton,iPhone 13 Pro Max,iPhone,256 GB,...,NZD,1.63,3317.73,Online (Apple.com),Apple Pay,Government,25–34,iOS 16,NaN,Returned

In [57]:
df["region"].unique()

array(['South America', 'Oceania', 'Europe', 'Asia', 'North America',
       'Africa', 'Europe/Asia', 'Middle East'], dtype=object)

# South America

In [58]:
South_America = df[ df["region"]== 'South America']

South_America_sum = round(South_America["unit_price_usd"].sum())

South_America_sum

737873

# South America 2022, 2023, 2024 Total Sales

In [59]:
South_America_2022_sum = round(South_America[ South_America["year"] == 2022]["unit_price_usd"].sum())
South_America_2023_sum = round(South_America[ South_America["year"] == 2023]["unit_price_usd"].sum())
South_America_2024_sum = round(South_America[ South_America["year"] == 2024]["unit_price_usd"].sum())

South_America_2022_sum,  South_America_2023_sum,  South_America_2024_sum

(242149, 244621, 251103)

# South America 2022, 2023, 2024 Total orders

In [60]:
South_America_2022_order = South_America[ South_America["year"] == 2022].shape[0]
South_America_2023_order = South_America[ South_America["year"] == 2023].shape[0]
South_America_2024_order = South_America[ South_America["year"] == 2024].shape[0]

South_America_2022_order, South_America_2023_order, South_America_2024_order

(338, 321, 331)

# Oceania

In [61]:
Oceania = df[ df["region"]== 'Oceania']

Oceania_sum = df[ df["region"]== 'Oceania'].shape[0]

Oceania_sum

506

In [62]:
Oceania_2022_sum = round(Oceania[ Oceania["year"] == 2022]["unit_price_usd"].sum())
Oceania_2023_sum = round(Oceania[ Oceania["year"] == 2023]["unit_price_usd"].sum())
Oceania_2024_sum = round(Oceania[ Oceania["year"] == 2024]["unit_price_usd"].sum())

Oceania_2022_sum,  Oceania_2023_sum,  Oceania_2024_sum

(168654, 114773, 122204)

In [63]:
Oceania_2022_order = Oceania[ Oceania["year"] == 2022].shape[0]
Oceania_2023_order = Oceania[ Oceania["year"] == 2023].shape[0]
Oceania_2024_order = Oceania[ Oceania["year"] == 2024].shape[0]

Oceania_2022_order, Oceania_2023_order, Oceania_2024_order

(189, 159, 158)

# Europe

In [64]:
Europe = df[ df["region"]== 'Europe']

Europe_sum = df[ df["region"]== 'Europe'].shape[0]

Europe_sum

3898

In [65]:
Europe_2022_sum = round(Europe[ Europe["year"] == 2022]["unit_price_usd"].sum())
Europe_2023_sum = round(Europe[ Europe["year"] == 2023]["unit_price_usd"].sum())
Europe_2024_sum = round(Europe[ Europe["year"] == 2024]["unit_price_usd"].sum())

Europe_2022_sum,  Europe_2023_sum,  Europe_2024_sum

(1037820, 1061268, 1083544)

In [66]:
Europe_2022_oder = Europe[ Europe["year"] == 2022].shape[0]
Europe_2023_oder = Europe[ Europe["year"] == 2023].shape[0]
Europe_2024_oder = Europe[ Europe["year"] == 2024].shape[0]

Europe_2022_oder, Europe_2023_oder, Europe_2024_oder

(1281, 1307, 1310)

# Asia

In [67]:
Asia = df[ df["region"]== 'Asia']

Asia_sum = df[ df["region"]== 'Asia'].shape[0]

Asia_sum

3435

In [68]:
Asia_2022_sum = round(Asia[ Asia["year"] == 2022]["unit_price_usd"].sum())
Asia_2023_sum = round(Asia[ Asia["year"] == 2023]["unit_price_usd"].sum())
Asia_2024_sum = round(Asia[ Asia["year"] == 2024]["unit_price_usd"].sum())

Asia_2022_sum,  Asia_2023_sum,  Asia_2024_sum

(886627, 965785, 973025)

In [69]:
Asia_2022_order = Asia[ Asia["year"] == 2022].shape[0]
Asia_2023_order = Asia[ Asia["year"] == 2023].shape[0]
Asia_2024_order = Asia[ Asia["year"] == 2024].shape[0]

Asia_2022_order, Asia_2023_order, Asia_2024_order

(1156, 1138, 1141)

# North America

In [70]:
North_America = df[ df["region"]== 'North America']
North_America_sum = df[ df["region"]== 'North America'].shape[0]

North_America_sum

762

In [71]:
North_America_2022_sum = round(North_America[ North_America["year"] == 2022]["unit_price_usd"].sum())
North_America_2023_sum = round(North_America[ North_America["year"] == 2023]["unit_price_usd"].sum())
North_America_2024_sum = round(North_America[ North_America["year"] == 2024]["unit_price_usd"].sum())

North_America_2022_sum,  North_America_2023_sum,  North_America_2024_sum

(217325, 198719, 203137)

In [72]:
North_America_2022_order = North_America[ North_America["year"] == 2022].shape[0]
North_America_2023_order = North_America[ North_America["year"] == 2023].shape[0]
North_America_2024_order = North_America[ North_America["year"] == 2024].shape[0]

North_America_2022_order, North_America_2023_order, North_America_2024_order

(271, 237, 254)

# Africa

In [73]:
Africa = df[ df["region"]== 'Africa']

Africa_sum = df[ df["region"]== 'Africa'].shape[0]

Africa_sum

943

In [74]:
Africa_2022_sum = round(Africa[ Africa["year"] == 2022]["unit_price_usd"].sum())
Africa_2023_sum = round(Africa[ Africa["year"] == 2023]["unit_price_usd"].sum())
Africa_2024_sum = round(Africa[ Africa["year"] == 2024]["unit_price_usd"].sum())

Africa_2022_sum,  Africa_2023_sum,  Africa_2024_sum

(243095, 235609, 265552)

In [75]:
Africa_2022_order = Africa[ Africa["year"] == 2022].shape[0]
Africa_2023_order = Africa[ Africa["year"] == 2023].shape[0]
Africa_2024_order = Africa[ Africa["year"] == 2024].shape[0]

Africa_2022_order, Africa_2023_order, Africa_2024_order

(325, 280, 338)

# Europe/Asia

In [76]:
Europe_Asia = df[ df["region"]== 'Europe/Asia']

Europe_Asia_sum = df[ df["region"]== 'Europe/Asia'].shape[0]

Europe_Asia_sum

480

In [77]:
Europe_Asia_2022_sum = round(Europe_Asia[ Europe_Asia["year"] == 2022]["unit_price_usd"].sum())
Europe_Asia_2023_sum = round(Europe_Asia[ Europe_Asia["year"] == 2023]["unit_price_usd"].sum())
Europe_Asia_2024_sum = round(Europe_Asia[ Europe_Asia["year"] == 2024]["unit_price_usd"].sum())

Europe_Asia_2022_sum,  Europe_Asia_2023_sum,  Europe_Asia_2024_sum

(110360, 107372, 153189)

In [78]:
Europe_Asia_2022_order = Europe_Asia[ Europe_Asia["year"] == 2022].shape[0]
Europe_Asia_2023_order = Europe_Asia[ Europe_Asia["year"] == 2023].shape[0]
Europe_Asia_2024_order = Europe_Asia[ Europe_Asia["year"] == 2024].shape[0]

Europe_Asia_2022_order, Europe_Asia_2023_order, Europe_Asia_2024_order

(162, 151, 167)

# Middle East

In [79]:
Middle_East = df[ df["region"]== 'Middle East']

Middle_East_sum = df[ df["region"]== 'Middle East'].shape[0]

Middle_East_sum

486

In [80]:
Middle_East_2022_sum = round(Middle_East[ Middle_East["year"] == 2022]["unit_price_usd"].sum())
Middle_East_2023_sum = round(Middle_East[ Middle_East["year"] == 2023]["unit_price_usd"].sum())
Middle_East_2024_sum = round(Middle_East[ Middle_East["year"] == 2024]["unit_price_usd"].sum())

Middle_East_2022_sum,  Middle_East_2023_sum,  Middle_East_2024_sum

(136719, 115811, 151826)

In [81]:
Middle_East_2022_order = Middle_East[ Middle_East["year"] == 2022].shape[0]
Middle_East_2023_order = Middle_East[ Middle_East["year"] == 2023].shape[0]
Middle_East_2024_order = Middle_East[ Middle_East["year"] == 2024].shape[0]

Middle_East_2022_order, Middle_East_2023_order, Middle_East_2024_order

(176, 142, 168)

# All Apple Categories

In [82]:
df["category"].unique()

array(['AirPods', 'Accessories', 'Apple Watch', 'Mac', 'iPhone', 'iPad'],
      dtype=object)

In [83]:
All_category = df['category'].nunique()

All_category

6

# AirPods

In [84]:
AirPods = df[ df["category"] == 'AirPods']

AirPods_sum = df[ df["category"] == 'AirPods'].shape[0]

AirPods_sum

1063

In [85]:
AirPods_2022 = AirPods[ AirPods['year'] == 2022].shape[0]
AirPods_2023 = AirPods[ AirPods['year'] == 2023].shape[0]
AirPods_2024 = AirPods[ AirPods['year'] == 2024].shape[0]

AirPods_2022, AirPods_2023, AirPods_2024

(367, 364, 332)

# Accessories

In [86]:
Accessories = df[ df["category"] == 'Accessories']

Accessories_sum = df[ df["category"] == 'Accessories'].shape[0]

Accessories_sum

2615

In [87]:
Accessories_2022 = Accessories[ Accessories['year'] == 2022].shape[0]
Accessories_2023 = Accessories[ Accessories['year'] == 2023].shape[0]
Accessories_2024 = Accessories[ Accessories['year'] == 2024].shape[0]

Accessories_2022, Accessories_2023, Accessories_2024

(899, 837, 879)

# Apple Watch

In [88]:
Apple_Watch = df[ df["category"] == 'Apple Watch']

Apple_Watch_sum = df[ df["category"] == 'Apple Watch'].shape[0]

Apple_Watch_sum

1126

In [89]:
Apple_Watch_2022 = Apple_Watch[ Apple_Watch['year'] == 2022].shape[0]
Apple_Watch_2023 = Apple_Watch[ Apple_Watch['year'] == 2023].shape[0]
Apple_Watch_2024 = Apple_Watch[ Apple_Watch['year'] == 2024].shape[0]

Apple_Watch_2022, Apple_Watch_2023, Apple_Watch_2024

(368, 361, 397)

# Mac

In [90]:
Mac = df[ df["category"] == 'Mac']

Mac_sum = df[ df["category"] == 'Mac'].shape[0]

Mac_sum

1873

In [91]:
Mac_2022 = Mac[ Mac['year'] == 2022].shape[0]
Mac_2023 = Mac[ Mac['year'] == 2023].shape[0]
Mac_2024 = Mac[ Mac['year'] == 2024].shape[0]

Mac_2022, Mac_2023, Mac_2024

(607, 633, 633)

# iPhone

In [92]:
iPhone = df[ df["category"] == 'iPhone']

iPhone_sum = df[ df["category"] == 'iPhone'].shape[0]

iPhone_sum

3444

In [93]:
iPhone_2022 = iPhone[ iPhone['year'] == 2022].shape[0]
iPhone_2023 = iPhone[ iPhone['year'] == 2023].shape[0]
iPhone_2024 = iPhone[ iPhone['year'] == 2024].shape[0]

iPhone_2022, iPhone_2023, iPhone_2024

(1166, 1116, 1162)

# iPad

In [94]:
iPad = df[ df["category"] == 'iPad']

iPad_sum = df[ df["category"] == 'iPad'].shape[0]

iPad_sum

1379

In [95]:
AirPods_2022 = AirPods[ AirPods['year'] == 2022].shape[0]
AirPods_2023 = AirPods[ AirPods['year'] == 2023].shape[0]
AirPods_2024 = AirPods[ AirPods['year'] == 2024].shape[0]

AirPods_2022, AirPods_2023, AirPods_2024

(367, 364, 332)

# Payment Method

In [96]:
df["payment_method"].unique()

array(['Cash', 'Debit Card', 'Credit Card', 'Net Banking', 'Gift Card',
       'Apple Pay', 'EMI / Installment'], dtype=object)

# Cash

In [97]:
Cash = df[ df["payment_method"]== 'Cash']

Cash.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
11056,2024-08-25,2024,Q3,August,United States,North America,Austin,Magic Keyboard,Accessories,NaN,...,USD,1.0,97.7,Authorized Reseller,Cash,Education,55+,NaN,NaN,Kept

# Cash orders and Sales

In [98]:
Cash_orders = Cash[ Cash["year"] == 2022].shape[0]
Cash_sum_sales = round(Cash[ Cash["year"] == 2022]["unit_price_usd"].sum())

Cash_orders, Cash_sum_sales

(514, 417445)

# Debit Card

In [99]:
Debit_Card = df[ df["payment_method"]== 'Debit Card']

Debit_Card.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
9560,2023-01-22,2023,Q1,January,Switzerland,Europe,Basel,AirPods Max,AirPods,NaN,...,CHF,0.88,938.15,Apple Store,Debit Card,Government,18–24,NaN,NaN,Kept

In [100]:
Debit_Card_orders = Debit_Card[ Debit_Card["year"] == 2022].shape[0]
Debit_Card_sum_sales = round(Debit_Card[ Debit_Card["year"] == 2022]["unit_price_usd"].sum())

Debit_Card_orders, Debit_Card_sum_sales

(527, 426337)

# Credit Card

In [101]:
Credit_Card = df[ df["payment_method"]== 'Credit Card']

Credit_Card.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
1867,2022-10-18,2022,Q4,October,Chile,South America,Santiago,iPhone 13,iPhone,256 GB,...,CLP,960.0,687484.8,Corporate / B2B,Credit Card,Individual,45–54,Other,3.3,Kept

In [102]:
Credit_Card_orders = Credit_Card[ Credit_Card["year"] == 2022].shape[0]
Credit_Card_sum_sales = round(Credit_Card[ Credit_Card["year"] == 2022]["unit_price_usd"].sum())

Credit_Card_orders, Credit_Card_sum_sales

(589, 426513)

# Net Banking

In [103]:
Net_Banking = df[ df["payment_method"]== 'Net Banking']

Net_Banking.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
11282,2022-09-23,2022,Q3,September,Vietnam,Asia,Bien Hoa,Apple Watch Ultra 2,Apple Watch,NaN,...,VND,24500.0,20210295.0,Apple Store,Net Banking,Government,45–54,NaN,4.7,Kept

In [104]:
Net_Banking_orders = Net_Banking[ Net_Banking["year"] == 2022].shape[0]
Net_Banking_sum_sales = round(Net_Banking[ Net_Banking["year"] == 2022]["unit_price_usd"].sum())

Net_Banking_orders, Net_Banking_sum_sales

(577, 450436)

# Gift Card

In [105]:
Gift_Card = df[ df["payment_method"]== 'Gift Card']

Gift_Card.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
9467,2023-08-15,2023,Q3,August,Sweden,Europe,Stockholm,iPhone SE (3rd Gen),iPhone,64 GB,...,SEK,10.55,9714.02,Apple Store,Gift Card,Individual,25–34,New User,4.7,Kept

In [106]:
Gift_Card_orders = Gift_Card[ Gift_Card["year"] == 2022].shape[0]
Gift_Card_sum_sales = round(Gift_Card[ Gift_Card["year"] == 2022]["unit_price_usd"].sum())

Gift_Card_orders, Gift_Card_sum_sales

(574, 449320)

# Apple Pay

In [107]:
Apple_Pay = df[ df["payment_method"]== 'Apple Pay']

Apple_Pay.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
3962,2024-12-17,2024,Q4,December,India,Asia,Ahmedabad,iPhone 13 Pro Max,iPhone,1 TB,...,INR,83.5,184533.33,Apple Store,Apple Pay,Business,45–54,iOS 15,NaN,Kept

In [108]:
Apple_Pay_orders = Apple_Pay[ Apple_Pay["year"] == 2022].shape[0]
Apple_Pay_sum_sales = round(Apple_Pay[ Apple_Pay["year"] == 2022]["unit_price_usd"].sum())

Apple_Pay_orders, Apple_Pay_sum_sales

(558, 416972)

# EMI / Installment

In [109]:
EMI_Installment = df[ df["payment_method"]== 'EMI / Installment']

EMI_Installment.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
4499,2024-06-12,2024,Q2,June,Ireland,Europe,Dundalk,MacBook Air 15-inch (M2),Mac,512 GB SSD,...,EUR,0.92,1048.2,Corporate / B2B,EMI / Installment,Education,25–34,NaN,4.6,Kept

In [110]:
EMI_Installment_orders = EMI_Installment[ EMI_Installment["year"] == 2022].shape[0]
EMI_Installment_sum_sales = round(EMI_Installment[ EMI_Installment["year"] == 2022]["unit_price_usd"].sum())

EMI_Installment_orders, EMI_Installment_sum_sales

(559, 455726)

# Customer segment
- 'Government'
- 'Business'
- 'Individual'
- 'Education

In [111]:
df["customer_segment"].unique()

array(['Government', 'Business', 'Individual', 'Education'], dtype=object)

# Government

In [112]:
Government = df[ df["customer_segment"] == 'Government']

Government.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
201,2022-05-27,2022,Q2,May,Argentina,South America,Salta,iPhone 15 Pro Max,iPhone,64 GB,...,ARS,907.0,2190477.56,Third-Party Retailer,Net Banking,Government,25–34,Android,3.9,Kept

# Government Order and Price sales

In [113]:
Government_sum_price = round(Government["unit_price_usd"].sum())

Government_orders = Government.shape[0]

Government_orders, Government_sum_price

(2892, 2258718)

# Government 2022, 2023, 2024

In [114]:
Government_2022 = round(Government[ Government["year"] == 2022]["unit_price_usd"].sum())
Government_2023 = round(Government[ Government["year"] == 2023]["unit_price_usd"].sum())
Government_2024 = round(Government[ Government["year"] == 2024]["unit_price_usd"].sum())

Government_2022, Government_2023,  Government_2024

(709077, 753362, 796279)

# Business

In [115]:
Business = df[ df["customer_segment"] == 'Business']

Business.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
333,2024-12-07,2024,Q4,December,Australia,Oceania,Canberra,Apple Watch Series 9,Apple Watch,NaN,...,AUD,1.53,603.68,Authorized Reseller,Debit Card,Business,18–24,NaN,3.1,Kept

In [116]:
Business_sum_price = round(Business["unit_price_usd"].sum())

Business_orders = Business.shape[0]

Business_orders, Business_sum_price

(2839, 2326487)

In [117]:
Business_2022 = round(Business[ Business["year"] == 2022]["unit_price_usd"].sum())
Business_2023 = round(Business[ Business["year"] == 2023]["unit_price_usd"].sum())
Business_2024 = round(Business[ Business["year"] == 2024]["unit_price_usd"].sum())

Business_2022, Business_2023, Business_2024

(766198, 743128, 817161)

# Individual

In [118]:
Individual = df[ df["customer_segment"] == 'Individual']

Individual.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
5725,2024-03-28,2024,Q1,March,Mexico,North America,León,iPhone 15 Pro,iPhone,1 TB,...,MXN,17.15,16403.8,Authorized Reseller,Cash,Individual,55+,New User,NaN,Kept

In [119]:
Individual_sum_price = round(Individual["unit_price_usd"].sum())

Individual_orders = Individual.shape[0]

Individual_orders, Individual_sum_price

(2885, 2266834)

In [120]:
Individual_2022 = round(Individual[ Individual["year"] == 2022]["unit_price_usd"].sum())
Individual_2023 = round(Individual[ Individual["year"] == 2023]["unit_price_usd"].sum())
Individual_2024 = round(Individual[ Individual["year"] == 2024]["unit_price_usd"].sum())

Individual_2022, Individual_2023, Individual_2024

(761488, 727601, 777745)

# Education

In [121]:
Education = df[ df["customer_segment"] == 'Education']

Education.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
9205,2024-10-20,2024,Q4,October,Spain,Europe,Palma,iPhone 15 Plus,iPhone,128 GB,...,EUR,0.92,802.7,Third-Party Retailer,Debit Card,Education,18–24,Other,3.6,Kept

In [122]:
Education_sum_price = round(Education["unit_price_usd"].sum())

Education_orders = Education.shape[0]

Education_orders, Education_sum_price

(2884, 2438250)

In [123]:
Education_2022 = round(Education[ Education["year"] == 2022]["unit_price_usd"].sum())
Education_2023 = round(Education[ Education["year"] == 2023]["unit_price_usd"].sum())
Education_2024 = round(Education[ Education["year"] == 2024]["unit_price_usd"].sum())

Education_2022, Education_2023, Education_2024

(805986, 819868, 812396)

# Customer age group
- '45–54'
- '18–24'
- '55+'
- '35–44'
-  '25–34'

In [124]:
df["customer_age_group"].unique()

array(['45–54', '18–24', '55+', '35–44', '25–34'], dtype=object)

# Customer 18-24

In [125]:
Customer_18_24 = df[ df["customer_age_group"] == '18–24']

Customer_18_24.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
9696,2022-01-07,2022,Q1,January,Switzerland,Europe,Lugano,iPhone 14 Plus,iPhone,1 TB,...,CHF,0.88,724.24,Apple Store,Apple Pay,Government,18–24,iOS 15,3.9,Kept

In [126]:
Customer_18_24_y_2022_sales = round(Customer_18_24[ Customer_18_24["year"] == 2022]["unit_price_usd"].sum())
Customer_18_24_y_2023_sales = round(Customer_18_24[ Customer_18_24["year"] == 2023]["unit_price_usd"].sum())
Customer_18_24_y_2024_sales = round(Customer_18_24[ Customer_18_24["year"] == 2024]["unit_price_usd"].sum())

Customer_18_24_y_2022_sales, Customer_18_24_y_2023_sales, Customer_18_24_y_2024_sales

(569743, 595582, 621623)

In [127]:
Customer_18_24_y_2022_orders = Customer_18_24[ Customer_18_24["year"] == 2022].shape[0]
Customer_18_24_y_2023_orders = Customer_18_24[ Customer_18_24["year"] == 2024].shape[0]
Customer_18_24_y_2024_orders = Customer_18_24[ Customer_18_24["year"] == 2024].shape[0]

Customer_18_24_y_2022_orders, Customer_18_24_y_2023_orders, Customer_18_24_y_2024_orders

(792, 770, 770)

# Customer 25–34

In [128]:
Customer_25_34 = df[ df["customer_age_group"] == '25–34']

Customer_25_34.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
3569,2024-05-13,2024,Q2,May,Germany,Europe,Frankfurt,HomePod (2nd Gen),Accessories,NaN,...,EUR,0.92,563.85,Authorized Reseller,Apple Pay,Individual,25–34,NaN,3.3,Kept

In [129]:
Customer_25_34_y_2022_sales = round(Customer_25_34[ Customer_25_34["year"] == 2022]["unit_price_usd"].sum())
Customer_25_34_y_2023_sales = round(Customer_25_34[ Customer_25_34["year"] == 2023]["unit_price_usd"].sum())
Customer_25_34_y_2024_sales = round(Customer_25_34[ Customer_25_34["year"] == 2024]["unit_price_usd"].sum())

Customer_25_34_y_2022_sales, Customer_25_34_y_2023_sales, Customer_25_34_y_2024_sales

(638198, 637193, 716084)

In [130]:
Customer_25_34_y_2022_orders = Customer_25_34[ Customer_25_34["year"] == 2022].shape[0]
Customer_25_34_y_2023_orders = Customer_25_34[ Customer_25_34["year"] == 2024].shape[0]
Customer_25_34_y_2024_orders = Customer_25_34[ Customer_25_34["year"] == 2024].shape[0]

Customer_25_34_y_2022_orders, Customer_25_34_y_2023_orders, Customer_25_34_y_2024_orders

(795, 811, 811)

# Customer 35–44

In [131]:
Customer_35_44 = df[ df["customer_age_group"] == '35–44']

Customer_35_44.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
158,2022-01-05,2022,Q1,January,Argentina,South America,Rosario,iPad Air (M1),iPad,64 GB,...,ARS,907.0,535102.79,Third-Party Retailer,Apple Pay,Business,35–44,NaN,3.2,Kept

In [132]:
Customer_35_44_y_2022_sales = round(Customer_35_44[ Customer_35_44["year"] == 2022]["unit_price_usd"].sum())
Customer_35_44_y_2023_sales = round(Customer_35_44[ Customer_35_44["year"] == 2023]["unit_price_usd"].sum())
Customer_35_44_y_2024_sales = round(Customer_35_44[ Customer_35_44["year"] == 2024]["unit_price_usd"].sum())

Customer_35_44_y_2022_sales, Customer_35_44_y_2023_sales, Customer_35_44_y_2024_sales

(622888, 582164, 659826)

In [133]:
Customer_35_44_y_2022_orders = Customer_35_44[ Customer_35_44["year"] == 2022].shape[0]
Customer_35_44_y_2023_orders = Customer_35_44[ Customer_35_44["year"] == 2024].shape[0]
Customer_35_44_y_2024_orders = Customer_35_44[ Customer_35_44["year"] == 2024].shape[0]

Customer_35_44_y_2022_orders, Customer_35_44_y_2023_orders, Customer_35_44_y_2024_orders

(766, 781, 781)

# Customer 45–54

In [134]:
Customer_45_54 = df[ df["customer_age_group"] == '45–54']

Customer_45_54.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
9394,2024-03-04,2024,Q1,March,Sweden,Europe,Linköping,HomePod mini,Accessories,NaN,...,SEK,10.55,1072.83,Apple Store,Debit Card,Government,45–54,NaN,3.3,Kept

In [135]:
Customer_45_54_y_2022_sales = round(Customer_45_54[ Customer_45_54["year"] == 2022]["unit_price_usd"].sum())
Customer_45_54_y_2023_sales = round(Customer_45_54[ Customer_45_54["year"] == 2023]["unit_price_usd"].sum())
Customer_45_54_y_2024_sales = round(Customer_45_54[ Customer_45_54["year"] == 2024]["unit_price_usd"].sum())

Customer_45_54_y_2022_sales, Customer_45_54_y_2023_sales, Customer_45_54_y_2024_sales

(597727, 587410, 621417)

In [136]:
Customer_45_54_y_2022_orders = Customer_45_54[ Customer_45_54["year"] == 2022].shape[0]
Customer_45_54_y_2023_orders = Customer_45_54[ Customer_45_54["year"] == 2024].shape[0]
Customer_45_54_y_2024_orders = Customer_45_54[ Customer_45_54["year"] == 2024].shape[0]

Customer_45_54_y_2022_orders, Customer_45_54_y_2023_orders, Customer_45_54_y_2024_orders

(783, 770, 770)

# Customer 55+

In [137]:
Customer_55 = df[ df["customer_age_group"] == '55+']

Customer_55.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
8503,2024-02-26,2024,Q1,February,Singapore,Asia,Singapore,iPhone 14 Pro,iPhone,1 TB,...,SGD,1.34,1294.6,Carrier Store,Credit Card,Government,55+,Other,4.3,Kept

In [138]:
Customer_55_y_2022_sales = round(Customer_55[ Customer_55["year"] == 2022]["unit_price_usd"].sum())
Customer_55_y_2023_sales = round(Customer_55[ Customer_55["year"] == 2023]["unit_price_usd"].sum())
Customer_55_y_2024_sales = round(Customer_55[ Customer_55["year"] == 2024]["unit_price_usd"].sum())

Customer_55_y_2022_sales, Customer_55_y_2023_sales, Customer_55_y_2024_sales

(614192, 641610, 584631)

In [139]:
Customer_55_y_2022_orders = Customer_55[ Customer_55["year"] == 2022].shape[0]
Customer_55_y_2023_orders = Customer_55[ Customer_55["year"] == 2024].shape[0]
Customer_55_y_2024_orders = Customer_55[ Customer_55["year"] == 2024].shape[0]

Customer_55_y_2022_orders, Customer_55_y_2023_orders, Customer_55_y_2024_orders

(762, 735, 735)

In [140]:
os.listdir("../data/cleaned_data")

['cleaned_data.csv']

In [141]:
df.to_csv("../data/cleaned_data/cleaned_data.csv")