## EDA = Exploratory Data Analysis

In [1]:
import pandas as pd
import numpy as np
import os
import warnings; warnings.filterwarnings("ignore")
import matplotlib.pyplot as plt
import seaborn as sns
import plotly as px

In [2]:
os.listdir('../data/raw/')

['12_apple_global_sales_dataset.csv']

In [3]:
df = pd.read_csv('../data/raw/12_apple_global_sales_dataset.csv')

In [4]:
df.shape

(11500, 27)

In [5]:
df.sample(2)

,sale_id,sale_date,year,quarter,month,country,region,city,product_name,category,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
3551,APPL-00003552,2024-10-07,2024,Q4,October,Germany,Europe,Düsseldorf,iPhone 13 Mini,iPhone,...,EUR,0.92,504.27,Apple Store,Gift Card,Individual,35–44,Other,NaN,Kept
2601,APPL-00002602,2022-07-24,2022,Q3,July,Denmark,Europe,Randers,AirPods (3rd Gen),AirPods,...,DKK,6.90,986.56,Corporate / B2B,EMI / Installment,Government,25–34,NaN,3.2,Kept

In [6]:
df.drop('sale_id', axis= 1 , inplace=True)

In [7]:
df.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
480,2022-07-19,2022,Q3,July,Australia,Oceania,Perth,iPad Pro 12.9-inch (M2),iPad,64 GB,...,AUD,1.53,3021.9,Third-Party Retailer,Debit Card,Government,35–44,NaN,NaN,Kept

In [8]:
df.isna().sum()

sale_date                    0
year                         0
quarter                      0
month                        0
country                      0
region                       0
city                         0
product_name                 0
category                     0
storage                   4804
color                        0
unit_price_usd               0
discount_pct                 0
units_sold                   0
discounted_price_usd         0
revenue_usd                  0
currency                     0
fx_rate_to_usd               0
revenue_local_currency       0
sales_channel                0
payment_method               0
customer_segment             0
customer_age_group           0
previous_device_os        8056
customer_rating           3360
return_status                0
dtype: int64

# Storage

In [9]:
df["storage"].value_counts()

storage
64 GB         944
256 GB        941
512 GB        924
128 GB        903
1 TB          889
1 TB SSD      473
2 TB SSD      472
512 GB SSD    471
256 GB SSD    457
2 TB          222
Name: count, dtype: int64

In [10]:
df["storage"].unique()

<ArrowStringArray>
[         nan,   '1 TB SSD',      '64 GB',     '128 GB',     '256 GB',
       '1 TB',   '2 TB SSD',     '512 GB', '512 GB SSD',       '2 TB',
 '256 GB SSD']
Length: 11, dtype: str

In [71]:
df["storage"].isna().sum()

np.int64(4804)

# previous_device_os

In [12]:
df["previous_device_os"].unique()

<ArrowStringArray>
[nan, 'iOS 16', 'New User', 'Other', 'iOS 15', 'Android', 'iOS 17']
Length: 7, dtype: str

In [13]:
df["previous_device_os"].value_counts()

previous_device_os
Android     595
iOS 16      587
Other       581
New User    571
iOS 15      556
iOS 17      554
Name: count, dtype: int64

In [14]:
df[ df["previous_device_os"].isna()].sample(10)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
1561,2024-05-12,2024,Q2,May,Canada,North America,Montreal,Apple Watch SE (2nd Gen),Apple Watch,NaN,...,CAD,1.36,341.06,Corporate / B2B,Debit Card,Business,25–34,NaN,3.9,Kept
3016,2023-05-30,2023,Q2,May,Finland,Europe,Kouvola,HomePod (2nd Gen),Accessories,NaN,...,EUR,0.92,868.41,Third-Party Retailer,Apple Pay,Business,45–54,NaN,4.2,Kept
6247,2024-12-09,2024,Q4,December,New Zealand,Oceania,Christchurch,AirPods Max,AirPods,NaN,...,NZD,1.63,949.18,Online (Apple.com),Credit Card,Government,18–24,NaN,4.4,Kept
6516,2022-10-20,2022,Q4,October,Nigeria,Africa,Ilorin,Magic Keyboard,Accessories,NaN,...,NGN,1550.00,295957.00,Carrier Store,Net Banking,Business,25–34,NaN,NaN,Kept
637,2022-05-16,2022,Q2,May,Austria,Europe,Saint Pölten,iPad Pro 12.9-inch (M2),iPad,1 TB,...,EUR,0.92,2003.72,Authorized Reseller,Apple Pay,Government,35–44,NaN,NaN,Kept
6096,2024-10-18,2024,Q4,October,Netherlands,Europe,Rotterdam,MacBook Air 13-inch (M2),Mac,1 TB SSD,...,EUR,0.92,2029.41,Corporate / B2B,Credit Card,Government,25–34,NaN,NaN,Kept
9241,2024-07-06,2024,Q3,July,Spain,Europe,Valencia,iPad Air (M1),iPad,64 GB,...,EUR,0.92,462.73,Online (Apple.com),Net Banking,Education,45–54,NaN,3.0,Exchanged
10595,2022-04-02,2022,Q2,April,UAE,Middle East,Ajman,AirPods (2nd Gen),AirPods,NaN,...,AED,3.67,1315.69,Online (Apple.com),Credit Card,Business,35–44,NaN,NaN,Kept
4892,2024-08-19,2024,Q3,August,Japan,Asia,Fukuoka,iPad (10th Generation),iPad,1 TB,...,JPY,149.80,258009.53,Third-Party Retailer,Debit Card,Business,25–34,NaN,4.7,Exchanged
3868,2024-06-05,2024,Q2,June,Hong Kong,Asia,Tuen Mun,MacBook Pro 16-inch (M3 Pro),Mac,256 GB SSD,...,HKD,7.82,41071.11,Apple Store,Cash,Government,25–34,NaN,3.5,Kept

# customer_rating

In [15]:
df["customer_rating"].value_counts()

customer_rating
4.0    434
4.4    433
4.6    433
3.7    432
3.2    428
4.2    426
3.4    422
4.8    414
4.3    413
3.5    407
4.1    405
3.6    399
3.9    399
3.3    398
4.7    394
4.9    393
3.8    376
3.1    373
4.5    366
3.0    198
5.0    197
Name: count, dtype: int64

In [72]:
df ["customer_rating"].isna().sum()

np.int64(3360)

In [16]:
df[ df ["customer_rating"].isna()].sample(10)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
11019,2023-08-19,2023,Q3,August,United Kingdom,Europe,Sheffield,Apple Watch SE (2nd Gen),Apple Watch,NaN,...,GBP,0.79,161.55,Apple Store,EMI / Installment,Government,18–24,NaN,NaN,Kept
7430,2024-02-14,2024,Q1,February,Poland,Europe,Katowice,iPad (10th Generation),iPad,1 TB,...,PLN,3.97,7577.30,Apple Store,Net Banking,Business,55+,NaN,NaN,Kept
9118,2023-08-02,2023,Q3,August,Spain,Europe,Córdoba,AirPods Max,AirPods,NaN,...,EUR,0.92,3468.33,Carrier Store,Apple Pay,Education,45–54,NaN,NaN,Kept
4622,2022-02-17,2022,Q1,February,Italy,Europe,Bari,MagSafe Charger,Accessories,NaN,...,EUR,0.92,124.79,Carrier Store,Debit Card,Education,25–34,NaN,NaN,Kept
3440,2023-02-20,2023,Q1,February,Germany,Europe,Berlin,Apple Watch Ultra 2,Apple Watch,NaN,...,EUR,0.92,1565.32,Online (Apple.com),Apple Pay,Education,55+,NaN,NaN,Exchanged
4895,2022-05-29,2022,Q2,May,Japan,Asia,Hiroshima,AirPods Pro (2nd Gen),AirPods,NaN,...,JPY,149.80,36404.40,Authorized Reseller,Credit Card,Individual,55+,NaN,NaN,Kept
7529,2022-06-21,2022,Q2,June,Poland,Europe,Poznan,Magic Keyboard,Accessories,NaN,...,PLN,3.97,640.92,Corporate / B2B,Gift Card,Government,45–54,NaN,NaN,Kept
403,2022-12-01,2022,Q4,December,Australia,Oceania,Hobart,HomePod mini,Accessories,NaN,...,AUD,1.53,152.92,Corporate / B2B,EMI / Installment,Government,18–24,NaN,NaN,Kept
10817,2022-09-29,2022,Q3,September,United Kingdom,Europe,Bristol,Magic Mouse,Accessories,NaN,...,GBP,0.79,61.69,Corporate / B2B,Credit Card,Individual,25–34,NaN,NaN,Kept
5801,2023-10-11,2023,Q4,October,Mexico,North America,Mérida,Apple Watch Series 9,Apple Watch,NaN,...,MXN,17.15,6607.04,Third-Party Retailer,Apple Pay,Education,18–24,NaN,NaN,Kept

# Duplicated

In [17]:
df.duplicated().sum()

np.int64(0)

In [18]:
df.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
8533,2024-06-30,2024,Q2,June,Singapore,Asia,Singapore,iPhone 14,iPhone,512 GB,...,SGD,1.34,1097.96,Carrier Store,Cash,Business,35–44,iOS 17,4.7,Kept

In [19]:
df["sale_date"].unique()

<ArrowStringArray>
['2022-01-03', '2022-01-04', '2022-05-18', '2022-05-23', '2022-07-13',
 '2022-07-31', '2022-08-01', '2022-08-04', '2023-01-14', '2023-01-26',
 ...
 '2023-07-10', '2022-03-09', '2023-12-31', '2023-07-30', '2022-01-27',
 '2022-07-06', '2024-09-23', '2024-04-06', '2024-03-13', '2024-08-12']
Length: 1096, dtype: str

In [20]:
df.columns

Index(['sale_date', 'year', 'quarter', 'month', 'country', 'region', 'city',
       'product_name', 'category', 'storage', 'color', 'unit_price_usd',
       'discount_pct', 'units_sold', 'discounted_price_usd', 'revenue_usd',
       'currency', 'fx_rate_to_usd', 'revenue_local_currency', 'sales_channel',
       'payment_method', 'customer_segment', 'customer_age_group',
       'previous_device_os', 'customer_rating', 'return_status'],
      dtype='str')

# Year 2022
- Q1
- Q2
- Q3
- Q4

# Start Here

In [401]:
All_Sales_price = round(df["unit_price_usd"].sum())
All_orders = df.shape[0]

All_Sales_price, All_orders

(9290289, 11500)

In [ ]:
year2022 = df [df['year'] == 2022]

year2022

3898

# 2022 Sum + sum price

In [131]:
year2022_sum = len (year2022)
year2022_sum_price = round(year2022["unit_price_usd"].sum())

year2022_sum, year2022_sum_price

(3898, 3042749)

# 2022 | Q1

In [22]:
Q1_y_2022 = year2022[year2022['quarter'] == 'Q1']

Q1_y_2022.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
1974,2022-03-07,2022,Q1,March,China,Asia,Chengdu,MagSafe Charger,Accessories,NaN,...,CNY,7.24,250.36,Corporate / B2B,EMI / Installment,Individual,45–54,NaN,4.3,Kept

In [132]:
Q1_y_2022_sum = len (Q1_y_2022)
Q1_y_2022_sum_price = round( Q1_y_2022["unit_price_usd"].sum())

Q1_y_2022_sum, Q1_y_2022_sum_price

(970, 774161)

# 2022 | Q2

In [23]:
Q2_y_2022 = year2022[year2022['quarter'] == 'Q2']

Q2_y_2022.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
4859,2022-05-13,2022,Q2,May,Italy,Europe,Verona,iMac 24-inch (M3),Mac,1 TB SSD,...,EUR,0.92,1110.98,Corporate / B2B,Apple Pay,Business,45–54,NaN,3.6,Kept

In [133]:
Q2_y_2022_sum = len (Q2_y_2022)
Q2_y_2022_sum_price = round(Q2_y_2022["unit_price_usd"].sum())

Q2_y_2022_sum, Q2_y_2022_sum_price

(946, 729307)

# 2022 | Q3

In [24]:
Q3_y_2022 = year2022[year2022['quarter'] == 'Q3']

Q3_y_2022.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
11427,2022-09-26,2022,Q3,September,Vietnam,Asia,Ho Chi Minh City,Magic Mouse,Accessories,NaN,...,VND,24500.0,1986950.0,Corporate / B2B,EMI / Installment,Business,25–34,NaN,3.9,Kept

In [134]:
Q3_y_2022_sum = len (Q3_y_2022)
Q3_y_2022_sum_price = round(Q3_y_2022["unit_price_usd"].sum())

Q3_y_2022_sum, Q3_y_2022_sum_price

(978, 782178)

# 2022 | Q4

In [25]:
Q4_y_2022 = year2022[year2022['quarter'] == 'Q4']

Q4_y_2022.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
10547,2022-10-20,2022,Q4,October,Turkey,Europe/Asia,Mersin,iMac 24-inch (M3),Mac,512 GB SSD,...,TRY,30.5,39977.26,Apple Store,Credit Card,Business,35–44,NaN,NaN,Kept

In [ ]:
Q4_y_2022_sum = len (Q4_y_2022)
Q4_y_2022_sum_price = round(Q4_y_2022["unit_price_usd"].sum())

Q4_y_2022_sum, Q4_y_2022_sum_price

(1004, np.float64(757102.78))

# Year 2023

In [26]:
year2023 = df [df['year'] == 2023]

year2023.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
4272,2023-12-20,2023,Q4,December,Indonesia,Asia,Medan,iPhone 14 Pro,iPhone,128 GB,...,IDR,15700.0,14914843.0,Carrier Store,Net Banking,Education,18–24,iOS 17,4.6,Kept

# 2023 sum + sum Price

In [128]:
year2023_sum = len (year2023)
year2023_sum_price = round(year2023["unit_price_usd"].sum(),  )

year2023_sum, year2023_sum_price

(3735, 3043959)

# 2023 | Q1

In [141]:
Q1_y_2023 = year2023[year2023["quarter"] == 'Q1']

Q1_y_2023.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
5098,2023-03-15,2023,Q1,March,Japan,Asia,Sendai,AirPods Max,AirPods,NaN,...,JPY,149.8,79816.44,Online (Apple.com),Debit Card,Individual,55+,NaN,4.3,Kept

In [143]:
Q1_y_2023_sum = len (Q1_y_2023)
Q1_y_2023_sum_price = round(Q1_y_2023["unit_price_usd"].sum())

Q1_y_2023_sum, Q1_y_2023_sum_price

(945, 801912)

# 2023 | Q2

In [28]:
Q2_y_2023 = year2023[year2023["quarter"] == 'Q2']

Q2_y_2023.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
2220,2023-05-01,2023,Q2,May,Colombia,South America,Bogotá,iPhone 13 Mini,iPhone,512 GB,...,COP,3960.0,4674859.2,Online (Apple.com),Cash,Education,25–34,New User,4.0,Kept

In [145]:
Q2_y_2023_sum = len (Q2_y_2023)
Q2_y_2023_sum_price = round(Q2_y_2023["unit_price_usd"].sum())

Q2_y_2023_sum, Q2_y_2023_sum_price

(934, 757829)

#  2023 | Q3

In [29]:
Q3_y_2023 = year2023[year2023["quarter"] == 'Q3']

Q3_y_2023.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
1956,2023-08-11,2023,Q3,August,China,Asia,Beijing,iPhone 13 Mini,iPhone,128 GB,...,CNY,7.24,8790.08,Carrier Store,EMI / Installment,Individual,18–24,iOS 15,NaN,Kept

In [146]:
Q3_y_2023_sum = len (Q3_y_2023)
Q3_y_2023_sum_price = round(Q3_y_2023["unit_price_usd"].sum())

Q3_y_2023_sum, Q3_y_2023_sum_price

(920, 730480)

# 2023 | Q4

In [30]:
Q4_y_2023 = year2023[year2023["quarter"] == 'Q4']

Q4_y_2023.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
3822,2023-11-19,2023,Q4,November,Hong Kong,Asia,Tsuen Wan,iPhone 14,iPhone,1 TB,...,HKD,7.82,6371.81,Authorized Reseller,Net Banking,Government,55+,New User,3.7,Returned

In [149]:
Q4_y_2023_sum = len (Q4_y_2023)
Q4_y_2023_sum_price = round( Q4_y_2023["unit_price_usd"].sum())

Q4_y_2023_sum, Q4_y_2023_sum_price

(936, 753738)

# Year 2024

In [31]:
year2024 = df [df['year'] == 2024]

year2024.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
6998,2024-10-16,2024,Q4,October,Pakistan,Asia,Lahore,Apple TV 4K (3rd Gen),Accessories,NaN,...,PKR,279.0,36557.37,Authorized Reseller,EMI / Installment,Business,18–24,NaN,NaN,Kept

In [153]:
year2024_sum = len (year2024)
year2024_sum_price = round(year2024["unit_price_usd"].sum())

year2024_sum, year2024_sum_price

(3867, 3203581)

# 2024 | Q1

In [156]:
Q1_y_2024 = year2024[ year2024["quarter"] == 'Q1']

Q1_y_2024.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
2320,2024-03-11,2024,Q1,March,Colombia,South America,Cúcuta,iPhone 13,iPhone,64 GB,...,COP,3960.0,14903460.0,Carrier Store,Debit Card,Government,18–24,iOS 17,3.9,Returned

In [158]:
Q1_y_2024_sum = len (Q1_y_2024)
Q1_y_2024_sum_price = round(Q1_y_2024["unit_price_usd"].sum())

Q1_y_2024_sum, Q1_y_2024_sum_price

(979, 795100)

# 2024 | Q2

In [33]:
Q2_y_2024 = year2024[ year2024["quarter"] == 'Q2']

Q2_y_2024.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
2246,2024-06-25,2024,Q2,June,Colombia,South America,Bucaramanga,Apple Watch SE (2nd Gen),Apple Watch,NaN,...,COP,3960.0,3062901.6,Carrier Store,Credit Card,Education,55+,NaN,NaN,Kept

In [162]:
Q2_y_2024_sum = len (Q2_y_2024)
Q2_y_2024_sum_price = round(Q2_y_2024["unit_price_usd"].sum())

Q2_y_2024_sum, Q2_y_2024_sum_price

(940, 744294)

# 2024 | Q3

In [34]:
Q3_y_2024 = year2024[ year2024["quarter"] == 'Q3']

Q3_y_2024.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
6510,2024-09-29,2024,Q3,September,Nigeria,Africa,Ibadan,Magic Trackpad,Accessories,NaN,...,NGN,1550.0,192076.0,Corporate / B2B,Cash,Education,25–34,NaN,NaN,Returned

In [161]:
Q3_y_2024_sum = len (Q3_y_2024)
Q3_y_2024_sum_price = round(Q3_y_2024["unit_price_usd"].sum())

Q3_y_2024_sum, Q3_y_2024_sum_price

(966, 793215)

# 2024 | Q4

In [35]:
Q4_y_2024 = year2024[ year2024["quarter"] == 'Q4']

Q4_y_2024.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
2798,2024-10-03,2024,Q4,October,Egypt,Africa,Luxor,Mac Pro (M2 Ultra),Mac,256 GB SSD,...,EGP,30.9,215364.04,Apple Store,Apple Pay,Government,25–34,NaN,5.0,Kept

In [160]:
Q4_y_2024_sum = len (Q4_y_2024)
Q4_y_2024_sum_price = round(Q4_y_2024["unit_price_usd"].sum())

Q4_y_2024_sum, Q4_y_2024_sum_price

(982, 870971)

# Unit price usd

In [167]:
All_unit_price = round(df["unit_price_usd"].sum())

All_unit_price

9290289

In [173]:
# Controll:
year2022_sum_price + year2023_sum_price + year2024_sum_price

9290289

# Region

In [36]:
df.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
5912,2024-05-24,2024,Q2,May,Mexico,North America,Zapopan,iPhone 15,iPhone,1 TB,...,MXN,17.15,13178.23,Third-Party Retailer,Credit Card,Government,35–44,iOS 16,4.2,Returned

In [37]:
df["region"].unique()

<ArrowStringArray>
['South America',       'Oceania',        'Europe',          'Asia',
 'North America',        'Africa',   'Europe/Asia',   'Middle East']
Length: 8, dtype: str

# South America

In [276]:
South_America = df[ df["region"]== 'South America']

South_America_sum = round(South_America["unit_price_usd"].sum())

South_America_sum

737873

# South America 2022, 2023, 2024 Total Sales

In [298]:
South_America_2022_sum = round(South_America[ South_America["year"] == 2022]["unit_price_usd"].sum())
South_America_2023_sum = round(South_America[ South_America["year"] == 2023]["unit_price_usd"].sum())
South_America_2024_sum = round(South_America[ South_America["year"] == 2024]["unit_price_usd"].sum())

South_America_2022_sum,  South_America_2023_sum,  South_America_2024_sum

(242149, 244621, 251103)

# South America 2022, 2023, 2024 Total orders

In [300]:
South_America_2022_order = South_America[ South_America["year"] == 2022].shape[0]
South_America_2023_order = South_America[ South_America["year"] == 2023].shape[0]
South_America_2024_order = South_America[ South_America["year"] == 2024].shape[0]

South_America_2022_order, South_America_2023_order, South_America_2024_order

(338, 321, 331)

# Oceania

In [203]:
Oceania = df[ df["region"]== 'Oceania']

Oceania_sum = df[ df["region"]== 'Oceania'].shape[0]

Oceania_sum

506

In [ ]:
Oceania_2022_sum = round(Oceania[ Oceania["year"] == 2022]["unit_price_usd"].sum())
Oceania_2023_sum = round(Oceania[ Oceania["year"] == 2023]["unit_price_usd"].sum())
Oceania_2024_sum = round(Oceania[ Oceania["year"] == 2024]["unit_price_usd"].sum())

Oceania_2022_sum,  Oceania_2023_sum,  Oceania_2024_sum

(168654, 114773, 122204)

In [302]:
Oceania_2022_order = Oceania[ Oceania["year"] == 2022].shape[0]
Oceania_2023_order = Oceania[ Oceania["year"] == 2023].shape[0]
Oceania_2024_order = Oceania[ Oceania["year"] == 2024].shape[0]

Oceania_2022_order, Oceania_2023_order, Oceania_2024_order

(189, 159, 158)

# Europe

In [204]:
Europe = df[ df["region"]== 'Europe']

Europe_sum = df[ df["region"]== 'Europe'].shape[0]

Europe_sum

3898

In [315]:
Europe_2022_sum = round(Europe[ Europe["year"] == 2022]["unit_price_usd"].sum())
Europe_2023_sum = round(Europe[ Europe["year"] == 2023]["unit_price_usd"].sum())
Europe_2024_sum = round(Europe[ Europe["year"] == 2024]["unit_price_usd"].sum())

Europe_2022_sum,  Europe_2023_sum,  Europe_2024_sum

(1037820, 1061268, 1083544)

In [304]:
Europe_2022_oder = Europe[ Europe["year"] == 2022].shape[0]
Europe_2023_oder = Europe[ Europe["year"] == 2023].shape[0]
Europe_2024_oder = Europe[ Europe["year"] == 2024].shape[0]

Europe_2022_oder, Europe_2023_oder, Europe_2024_oder

(1281, 1307, 1310)

# Asia

In [206]:
Asia = df[ df["region"]== 'Asia']

Asia_sum = df[ df["region"]== 'Asia'].shape[0]

Asia_sum

3435

In [316]:
Asia_2022_sum = round(Asia[ Asia["year"] == 2022]["unit_price_usd"].sum())
Asia_2023_sum = round(Asia[ Asia["year"] == 2023]["unit_price_usd"].sum())
Asia_2024_sum = round(Asia[ Asia["year"] == 2024]["unit_price_usd"].sum())

Asia_2022_sum,  Asia_2023_sum,  Asia_2024_sum

(886627, 965785, 973025)

In [306]:
Asia_2022_order = Asia[ Asia["year"] == 2022].shape[0]
Asia_2023_order = Asia[ Asia["year"] == 2023].shape[0]
Asia_2024_order = Asia[ Asia["year"] == 2024].shape[0]

Asia_2022_order, Asia_2023_order, Asia_2024_order

(1156, 1138, 1141)

# North America

In [209]:
North_America = df[ df["region"]== 'North America']
North_America_sum = df[ df["region"]== 'North America'].shape[0]

North_America_sum

762

In [317]:
North_America_2022_sum = round(North_America[ North_America["year"] == 2022]["unit_price_usd"].sum())
North_America_2023_sum = round(North_America[ North_America["year"] == 2023]["unit_price_usd"].sum())
North_America_2024_sum = round(North_America[ North_America["year"] == 2024]["unit_price_usd"].sum())

North_America_2022_sum,  North_America_2023_sum,  North_America_2024_sum

(217325, 198719, 203137)

In [308]:
North_America_2022_order = North_America[ North_America["year"] == 2022].shape[0]
North_America_2023_order = North_America[ North_America["year"] == 2023].shape[0]
North_America_2024_order = North_America[ North_America["year"] == 2024].shape[0]

North_America_2022_order, North_America_2023_order, North_America_2024_order

(271, 237, 254)

# Africa

In [211]:
Africa = df[ df["region"]== 'Africa']

Africa_sum = df[ df["region"]== 'Africa'].shape[0]

Africa_sum

943

In [318]:
Africa_2022_sum = round(Africa[ Africa["year"] == 2022]["unit_price_usd"].sum())
Africa_2023_sum = round(Africa[ Africa["year"] == 2023]["unit_price_usd"].sum())
Africa_2024_sum = round(Africa[ Africa["year"] == 2024]["unit_price_usd"].sum())

Africa_2022_sum,  Africa_2023_sum,  Africa_2024_sum

(243095, 235609, 265552)

In [310]:
Africa_2022_order = Africa[ Africa["year"] == 2022].shape[0]
Africa_2023_order = Africa[ Africa["year"] == 2023].shape[0]
Africa_2024_order = Africa[ Africa["year"] == 2024].shape[0]

Africa_2022_order, Africa_2023_order, Africa_2024_order

(325, 280, 338)

# Europe/Asia

In [213]:
Europe_Asia = df[ df["region"]== 'Europe/Asia']

Europe_Asia_sum = df[ df["region"]== 'Europe/Asia'].shape[0]

Europe_Asia_sum

480

In [319]:
Europe_Asia_2022_sum = round(Europe_Asia[ Europe_Asia["year"] == 2022]["unit_price_usd"].sum())
Europe_Asia_2023_sum = round(Europe_Asia[ Europe_Asia["year"] == 2023]["unit_price_usd"].sum())
Europe_Asia_2024_sum = round(Europe_Asia[ Europe_Asia["year"] == 2024]["unit_price_usd"].sum())

Europe_Asia_2022_sum,  Europe_Asia_2023_sum,  Europe_Asia_2024_sum

(110360, 107372, 153189)

In [314]:
Europe_Asia_2022_order = Europe_Asia[ Europe_Asia["year"] == 2022].shape[0]
Europe_Asia_2023_order = Europe_Asia[ Europe_Asia["year"] == 2023].shape[0]
Europe_Asia_2024_order = Europe_Asia[ Europe_Asia["year"] == 2024].shape[0]

Europe_Asia_2022_order, Europe_Asia_2023_order, Europe_Asia_2024_order

(162, 151, 167)

# Middle East

In [ ]:
Middle_East = df[ df["region"]== 'Middle East']

Middle_East_sum = df[ df["region"]== 'Middle East'].shape[0]

Middle_East_sum

486

In [320]:
Middle_East_2022_sum = round(Middle_East[ Middle_East["year"] == 2022]["unit_price_usd"].sum())
Middle_East_2023_sum = round(Middle_East[ Middle_East["year"] == 2023]["unit_price_usd"].sum())
Middle_East_2024_sum = round(Middle_East[ Middle_East["year"] == 2024]["unit_price_usd"].sum())

Middle_East_2022_sum,  Middle_East_2023_sum,  Middle_East_2024_sum

(136719, 115811, 151826)

In [321]:
Middle_East_2022_order = Middle_East[ Middle_East["year"] == 2022].shape[0]
Middle_East_2023_order = Middle_East[ Middle_East["year"] == 2023].shape[0]
Middle_East_2024_order = Middle_East[ Middle_East["year"] == 2024].shape[0]

Middle_East_2022_order, Middle_East_2023_order, Middle_East_2024_order

(176, 142, 168)

# All Apple Categories

In [ ]:
df["category"].unique()

<ArrowStringArray>
['AirPods', 'Accessories', 'Apple Watch', 'Mac', 'iPhone', 'iPad']
Length: 6, dtype: str

In [234]:
All_category = df['category'].nunique()

All_category

6

# AirPods

In [222]:
AirPods = df[ df["category"] == 'AirPods']

AirPods_sum = df[ df["category"] == 'AirPods'].shape[0]

AirPods_sum

1063

In [229]:
AirPods_2022 = AirPods[ AirPods['year'] == 2022].shape[0]
AirPods_2023 = AirPods[ AirPods['year'] == 2023].shape[0]
AirPods_2024 = AirPods[ AirPods['year'] == 2024].shape[0]

AirPods_2022, AirPods_2023, AirPods_2024

(367, 364, 332)

# Accessories

In [235]:
Accessories = df[ df["category"] == 'Accessories']

Accessories_sum = df[ df["category"] == 'Accessories'].shape[0]

Accessories_sum

2615

In [236]:
Accessories_2022 = Accessories[ Accessories['year'] == 2022].shape[0]
Accessories_2023 = Accessories[ Accessories['year'] == 2023].shape[0]
Accessories_2024 = Accessories[ Accessories['year'] == 2024].shape[0]

Accessories_2022, Accessories_2023, Accessories_2024

(899, 837, 879)

# Apple Watch

In [237]:
Apple_Watch = df[ df["category"] == 'Apple Watch']

Apple_Watch_sum = df[ df["category"] == 'Apple Watch'].shape[0]

Apple_Watch_sum

1126

In [238]:
Apple_Watch_2022 = Apple_Watch[ Apple_Watch['year'] == 2022].shape[0]
Apple_Watch_2023 = Apple_Watch[ Apple_Watch['year'] == 2023].shape[0]
Apple_Watch_2024 = Apple_Watch[ Apple_Watch['year'] == 2024].shape[0]

Apple_Watch_2022, Apple_Watch_2023, Apple_Watch_2024

(368, 361, 397)

# Mac

In [239]:
Mac = df[ df["category"] == 'Mac']

Mac_sum = df[ df["category"] == 'Mac'].shape[0]

Mac_sum

1873

In [240]:
Mac_2022 = Mac[ Mac['year'] == 2022].shape[0]
Mac_2023 = Mac[ Mac['year'] == 2023].shape[0]
Mac_2024 = Mac[ Mac['year'] == 2024].shape[0]

Mac_2022, Mac_2023, Mac_2024

(607, 633, 633)

# iPhone

In [241]:
iPhone = df[ df["category"] == 'iPhone']

iPhone_sum = df[ df["category"] == 'iPhone'].shape[0]

iPhone_sum

3444

In [242]:
iPhone_2022 = iPhone[ iPhone['year'] == 2022].shape[0]
iPhone_2023 = iPhone[ iPhone['year'] == 2023].shape[0]
iPhone_2024 = iPhone[ iPhone['year'] == 2024].shape[0]

iPhone_2022, iPhone_2023, iPhone_2024

(1166, 1116, 1162)

# iPad

In [243]:
iPad = df[ df["category"] == 'iPad']

iPad_sum = df[ df["category"] == 'iPad'].shape[0]

iPad_sum

1379

In [ ]:
AirPods_2022 = AirPods[ AirPods['year'] == 2022].shape[0]
AirPods_2023 = AirPods[ AirPods['year'] == 2023].shape[0]
AirPods_2024 = AirPods[ AirPods['year'] == 2024].shape[0]

AirPods_2022, AirPods_2023, AirPods_2024

# Payment Method

In [53]:
df["payment_method"].unique()

<ArrowStringArray>
[             'Cash',        'Debit Card',       'Credit Card',
       'Net Banking',         'Gift Card',         'Apple Pay',
 'EMI / Installment']
Length: 7, dtype: str

# Cash

In [54]:
Cash = df[ df["payment_method"]== 'Cash']

Cash.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
1651,2023-08-28,2023,Q3,August,Canada,North America,Toronto,AirPods Max,AirPods,NaN,...,CAD,1.36,787.89,Carrier Store,Cash,Business,25–34,NaN,NaN,Kept

# Cash orders and Sales

In [328]:
Cash_orders = Cash[ Cash["year"] == 2022].shape[0]
Cash_sum_sales = round(Cash[ Cash["year"] == 2022]["unit_price_usd"].sum())

Cash_orders, Cash_sum_sales

(514, 417445)

# Debit Card

In [55]:
Debit_Card = df[ df["payment_method"]== 'Debit Card']

Debit_Card.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
331,2024-09-17,2024,Q3,September,Australia,Oceania,Canberra,AirPods (2nd Gen),AirPods,NaN,...,AUD,1.53,803.13,Corporate / B2B,Debit Card,Individual,35–44,NaN,4.3,Returned

In [329]:
Debit_Card_orders = Debit_Card[ Debit_Card["year"] == 2022].shape[0]
Debit_Card_sum_sales = round(Debit_Card[ Debit_Card["year"] == 2022]["unit_price_usd"].sum())

Debit_Card_orders, Debit_Card_sum_sales

(527, 426337)

# Credit Card

In [56]:
Credit_Card = df[ df["payment_method"]== 'Credit Card']

Credit_Card.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
10129,2022-01-23,2022,Q1,January,Thailand,Asia,Hat Yai,MacBook Pro 14-inch (M3),Mac,2 TB SSD,...,THB,35.2,216510.62,Apple Store,Credit Card,Government,35–44,NaN,4.1,Kept

In [331]:
Credit_Card_orders = Credit_Card[ Credit_Card["year"] == 2022].shape[0]
Credit_Card_sum_sales = round(Credit_Card[ Credit_Card["year"] == 2022]["unit_price_usd"].sum())

Credit_Card_orders, Credit_Card_sum_sales

(589, 426513)

# Net Banking

In [57]:
Net_Banking = df[ df["payment_method"]== 'Net Banking']

Net_Banking.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
5407,2022-09-24,2022,Q3,September,Malaysia,Asia,George Town,iPad Air (M1),iPad,2 TB,...,MYR,4.71,2760.25,Carrier Store,Net Banking,Business,35–44,NaN,NaN,Kept

In [332]:
Net_Banking_orders = Net_Banking[ Net_Banking["year"] == 2022].shape[0]
Net_Banking_sum_sales = round(Net_Banking[ Net_Banking["year"] == 2022]["unit_price_usd"].sum())

Net_Banking_orders, Net_Banking_sum_sales

(577, 450436)

# Gift Card

In [58]:
Gift_Card = df[ df["payment_method"]== 'Gift Card']

Gift_Card.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
7109,2022-03-13,2022,Q1,March,Philippines,Asia,Antipolo,iPad Pro 11-inch (M2),iPad,1 TB,...,PHP,56.5,174878.8,Authorized Reseller,Gift Card,Business,55+,NaN,NaN,Kept

In [333]:
Gift_Card_orders = Gift_Card[ Gift_Card["year"] == 2022].shape[0]
Gift_Card_sum_sales = round(Gift_Card[ Gift_Card["year"] == 2022]["unit_price_usd"].sum())

Gift_Card_orders, Gift_Card_sum_sales

(574, 449320)

# Apple Pay

In [59]:
Apple_Pay = df[ df["payment_method"]== 'Apple Pay']

Apple_Pay.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
5130,2022-01-16,2022,Q1,January,Japan,Asia,Yokohama,iPhone 14 Pro,iPhone,1 TB,...,JPY,149.8,264921.3,Carrier Store,Apple Pay,Government,18–24,Android,3.2,Kept

In [334]:
Apple_Pay_orders = Apple_Pay[ Apple_Pay["year"] == 2022].shape[0]
Apple_Pay_sum_sales = round(Apple_Pay[ Apple_Pay["year"] == 2022]["unit_price_usd"].sum())

Apple_Pay_orders, Apple_Pay_sum_sales

(558, 416972)

# EMI / Installment

In [60]:
EMI_Installment = df[ df["payment_method"]== 'EMI / Installment']

EMI_Installment.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
1720,2022-07-01,2022,Q3,July,Chile,South America,Antofagasta,Apple Watch Series 8,Apple Watch,NaN,...,CLP,960.0,901756.8,Authorized Reseller,EMI / Installment,Individual,35–44,NaN,4.0,Kept

In [335]:
EMI_Installment_orders = EMI_Installment[ EMI_Installment["year"] == 2022].shape[0]
EMI_Installment_sum_sales = round(EMI_Installment[ EMI_Installment["year"] == 2022]["unit_price_usd"].sum())

EMI_Installment_orders, EMI_Installment_sum_sales

(559, 455726)

# Customer segment
- 'Government'
- 'Business'
- 'Individual'
- 'Education

In [63]:
df["customer_segment"].unique()

<ArrowStringArray>
['Government', 'Business', 'Individual', 'Education']
Length: 4, dtype: str

# Government

In [65]:
Government = df[ df["customer_segment"] == 'Government']

Government.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
3783,2023-10-21,2023,Q4,October,Hong Kong,Asia,Sha Tin,HomePod (2nd Gen),Accessories,NaN,...,HKD,7.82,6732.79,Authorized Reseller,Gift Card,Government,45–54,NaN,NaN,Kept

# Government Order and Price sales

In [364]:
Government_sum_price = round(Government["unit_price_usd"].sum())

Government_orders = Government.shape[0]

Government_orders, Government_sum_price

(2892, 2258718)

# Government 2022, 2023, 2024

In [363]:
Government_2022 = round(Government[ Government["year"] == 2022]["unit_price_usd"].sum())
Government_2023 = round(Government[ Government["year"] == 2023]["unit_price_usd"].sum())
Government_2024 = round(Government[ Government["year"] == 2024]["unit_price_usd"].sum())

Government_2022, Government_2023,  Government_2024

(709077, 753362, 796279)

# Business

In [67]:
Business = df[ df["customer_segment"] == 'Business']

Business.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
2171,2022-12-21,2022,Q4,December,China,Asia,Zhengzhou,iPhone 13,iPhone,512 GB,...,CNY,7.24,4824.3,Carrier Store,Debit Card,Business,25–34,iOS 17,NaN,Kept

In [365]:
Business_sum_price = round(Business["unit_price_usd"].sum())

Business_orders = Business.shape[0]

Business_orders, Business_sum_price

(2839, 2326487)

In [352]:
Business_2022 = round(Business[ Business["year"] == 2022]["unit_price_usd"].sum())
Business_2023 = round(Business[ Business["year"] == 2023]["unit_price_usd"].sum())
Business_2024 = round(Business[ Business["year"] == 2024]["unit_price_usd"].sum())

Business_2022, Business_2023, Business_2024

(766198, 743128, 817161)

# Individual

In [68]:
Individual = df[ df["customer_segment"] == 'Individual']

Individual.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
5569,2022-11-01,2022,Q4,November,Malaysia,Asia,Petaling Jaya,USB-C Woven Charge Cable,Accessories,NaN,...,MYR,4.71,135.51,Online (Apple.com),Net Banking,Individual,45–54,NaN,NaN,Kept

In [366]:
Individual_sum_price = round(Individual["unit_price_usd"].sum())

Individual_orders = Individual.shape[0]

Individual_orders, Individual_sum_price

(2885, 2266834)

In [368]:
Individual_2022 = round(Individual[ Individual["year"] == 2022]["unit_price_usd"].sum())
Individual_2023 = round(Individual[ Individual["year"] == 2023]["unit_price_usd"].sum())
Individual_2024 = round(Individual[ Individual["year"] == 2024]["unit_price_usd"].sum())

Individual_2022, Individual_2023, Individual_2024

(761488, 727601, 777745)

# Education

In [69]:
Education = df[ df["customer_segment"] == 'Education']

Education.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
393,2024-11-23,2024,Q4,November,Australia,Oceania,Gold Coast,Apple TV 4K (3rd Gen),Accessories,NaN,...,AUD,1.53,170.69,Authorized Reseller,Debit Card,Education,18–24,NaN,3.9,Exchanged

In [367]:
Education_sum_price = round(Education["unit_price_usd"].sum())

Education_orders = Education.shape[0]

Education_orders, Education_sum_price

(2884, 2438250)

In [369]:
Education_2022 = round(Education[ Education["year"] == 2022]["unit_price_usd"].sum())
Education_2023 = round(Education[ Education["year"] == 2023]["unit_price_usd"].sum())
Education_2024 = round(Education[ Education["year"] == 2024]["unit_price_usd"].sum())

Education_2022, Education_2023, Education_2024

(805986, 819868, 812396)

# Customer age group
- '45–54'
- '18–24'
- '55+'
- '35–44'
-  '25–34'

In [73]:
df["customer_age_group"].unique()

<ArrowStringArray>
['45–54', '18–24', '55+', '35–44', '25–34']
Length: 5, dtype: str

# Customer 18-24

In [76]:
Customer_18_24 = df[ df["customer_age_group"] == '18–24']

Customer_18_24.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
11131,2022-02-20,2022,Q1,February,United States,North America,Houston,iPad (10th Generation),iPad,128 GB,...,USD,1.0,846.56,Apple Store,Apple Pay,Individual,18–24,NaN,3.4,Kept

In [380]:
Customer_18_24_y_2022_sales = round(Customer_18_24[ Customer_18_24["year"] == 2022]["unit_price_usd"].sum())
Customer_18_24_y_2023_sales = round(Customer_18_24[ Customer_18_24["year"] == 2023]["unit_price_usd"].sum())
Customer_18_24_y_2024_sales = round(Customer_18_24[ Customer_18_24["year"] == 2024]["unit_price_usd"].sum())

Customer_18_24_y_2022_sales, Customer_18_24_y_2023_sales, Customer_18_24_y_2024_sales

(569743, 595582, 621623)

In [383]:
Customer_18_24_y_2022_orders = Customer_18_24[ Customer_18_24["year"] == 2022].shape[0]
Customer_18_24_y_2023_orders = Customer_18_24[ Customer_18_24["year"] == 2024].shape[0]
Customer_18_24_y_2024_orders = Customer_18_24[ Customer_18_24["year"] == 2024].shape[0]

Customer_18_24_y_2022_orders, Customer_18_24_y_2023_orders, Customer_18_24_y_2024_orders

(792, 770, 770)

# Customer 25–34

In [78]:
Customer_25_34 = df[ df["customer_age_group"] == '25–34']

Customer_25_34.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
4347,2023-04-21,2023,Q2,April,Indonesia,Asia,Surabaya,Magic Mouse,Accessories,NaN,...,IDR,15700.0,1176087.0,Authorized Reseller,EMI / Installment,Education,25–34,NaN,3.1,Returned

In [382]:
Customer_25_34_y_2022_sales = round(Customer_25_34[ Customer_25_34["year"] == 2022]["unit_price_usd"].sum())
Customer_25_34_y_2023_sales = round(Customer_25_34[ Customer_25_34["year"] == 2023]["unit_price_usd"].sum())
Customer_25_34_y_2024_sales = round(Customer_25_34[ Customer_25_34["year"] == 2024]["unit_price_usd"].sum())

Customer_25_34_y_2022_sales, Customer_25_34_y_2023_sales, Customer_25_34_y_2024_sales

(638198, 637193, 716084)

In [384]:
Customer_25_34_y_2022_orders = Customer_25_34[ Customer_25_34["year"] == 2022].shape[0]
Customer_25_34_y_2023_orders = Customer_25_34[ Customer_25_34["year"] == 2024].shape[0]
Customer_25_34_y_2024_orders = Customer_25_34[ Customer_25_34["year"] == 2024].shape[0]

Customer_25_34_y_2022_orders, Customer_25_34_y_2023_orders, Customer_25_34_y_2024_orders

(795, 811, 811)

# Customer 35–44

In [77]:
Customer_35_44 = df[ df["customer_age_group"] == '35–44']

Customer_35_44.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
1111,2024-06-30,2024,Q2,June,Belgium,Europe,Leuven,iPad Pro 11-inch (M2),iPad,256 GB,...,EUR,0.92,757.56,Online (Apple.com),Debit Card,Business,35–44,NaN,NaN,Returned

In [385]:
Customer_35_44_y_2022_sales = round(Customer_35_44[ Customer_35_44["year"] == 2022]["unit_price_usd"].sum())
Customer_35_44_y_2023_sales = round(Customer_35_44[ Customer_35_44["year"] == 2023]["unit_price_usd"].sum())
Customer_35_44_y_2024_sales = round(Customer_35_44[ Customer_35_44["year"] == 2024]["unit_price_usd"].sum())

Customer_35_44_y_2022_sales, Customer_35_44_y_2023_sales, Customer_35_44_y_2024_sales

(622888, 582164, 659826)

In [386]:
Customer_35_44_y_2022_orders = Customer_35_44[ Customer_35_44["year"] == 2022].shape[0]
Customer_35_44_y_2023_orders = Customer_35_44[ Customer_35_44["year"] == 2024].shape[0]
Customer_35_44_y_2024_orders = Customer_35_44[ Customer_35_44["year"] == 2024].shape[0]

Customer_35_44_y_2022_orders, Customer_35_44_y_2023_orders, Customer_35_44_y_2024_orders

(766, 781, 781)

# Customer 45–54

In [79]:
Customer_45_54 = df[ df["customer_age_group"] == '45–54']

Customer_45_54.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
1350,2024-06-14,2024,Q2,June,Brazil,South America,Manaus,Apple Watch Ultra 2,Apple Watch,NaN,...,BRL,4.97,12048.62,Third-Party Retailer,Apple Pay,Individual,45–54,NaN,3.8,Kept

In [387]:
Customer_45_54_y_2022_sales = round(Customer_45_54[ Customer_45_54["year"] == 2022]["unit_price_usd"].sum())
Customer_45_54_y_2023_sales = round(Customer_45_54[ Customer_45_54["year"] == 2023]["unit_price_usd"].sum())
Customer_45_54_y_2024_sales = round(Customer_45_54[ Customer_45_54["year"] == 2024]["unit_price_usd"].sum())

Customer_45_54_y_2022_sales, Customer_45_54_y_2023_sales, Customer_45_54_y_2024_sales

(597727, 587410, 621417)

In [388]:
Customer_45_54_y_2022_orders = Customer_45_54[ Customer_45_54["year"] == 2022].shape[0]
Customer_45_54_y_2023_orders = Customer_45_54[ Customer_45_54["year"] == 2024].shape[0]
Customer_45_54_y_2024_orders = Customer_45_54[ Customer_45_54["year"] == 2024].shape[0]

Customer_45_54_y_2022_orders, Customer_45_54_y_2023_orders, Customer_45_54_y_2024_orders

(783, 770, 770)

# Customer 55+

In [80]:
Customer_55 = df[ df["customer_age_group"] == '55+']

Customer_55.sample(1)

,sale_date,year,quarter,month,country,region,city,product_name,category,storage,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
4121,2023-06-03,2023,Q2,June,India,Asia,Thane,iPad Air (M1),iPad,64 GB,...,INR,83.5,44157.31,Online (Apple.com),Net Banking,Business,55+,NaN,4.8,Kept

In [389]:
Customer_55_y_2022_sales = round(Customer_55[ Customer_55["year"] == 2022]["unit_price_usd"].sum())
Customer_55_y_2023_sales = round(Customer_55[ Customer_55["year"] == 2023]["unit_price_usd"].sum())
Customer_55_y_2024_sales = round(Customer_55[ Customer_55["year"] == 2024]["unit_price_usd"].sum())

Customer_55_y_2022_sales, Customer_55_y_2023_sales, Customer_55_y_2024_sales

(614192, 641610, 584631)

In [390]:
Customer_55_y_2022_orders = Customer_55[ Customer_55["year"] == 2022].shape[0]
Customer_55_y_2023_orders = Customer_55[ Customer_55["year"] == 2024].shape[0]
Customer_55_y_2024_orders = Customer_55[ Customer_55["year"] == 2024].shape[0]

Customer_55_y_2022_orders, Customer_55_y_2023_orders, Customer_55_y_2024_orders

(762, 735, 735)

In [406]:
os.listdir("../data/cleaned_data")

['cleaned_data.csv']

In [408]:
df.to_csv("../data/cleaned_data/cleaned_data.csv")